<?php
/**
 * Generated by Haxe 4.0.0-rc.2+77068e1
 * Haxe source file: /Users/ut/haxe/haxe_libraries/tink_http_middleware/0.1.0/github/82c73bb5c4cd37a67f711b71a42e7ec2031d6894/src/tink/http/middleware/Static.hx
 */

namespace tink\http\middleware;

use \tink\http\IncomingRequest;
use \php\_Boot\HxAnon;
use \tink\http\HeaderField;
use \tink\core\_Future\SyncFuture;
use \tink\io\RealSourceTools;
use \php\Boot;
use \mime\Mime;
use \tink\io\_Source\Source_Impl_;
use \tink\core\TypedError;
use \tink\http\Header;
use \tink\streams\StreamObject;
use \asys\io\File;
use \tink\core\Outcome;
use \tink\http\ResponseHeaderBase;
use \tink\core\_Lazy\LazyConst;
use \php\_Boot\HxString;
use \tink\core\_Future\Future_Impl_;
use \tink\http\_Header\HeaderValue_Impl_;
use \tink\http\_Response\OutgoingResponseData;
use \tink\core\_Promise\Promise_Impl_;
use \asys\FileSystem;
use \haxe\io\Path;
use \tink\core\_Future\FutureObject;
use \tink\http\HandlerObject;

class StaticHandler implements HandlerObject {
	/**
	 * @var HandlerObject
	 */
	public $handler;
	/**
	 * @var TypedError
	 */
	public $notFound;
	/**
	 * @var object
	 */
	public $options;
	/**
	 * @var string
	 */
	public $prefix;
	/**
	 * @var string
	 */
	public $root;

	/**
	 * @param string $root
	 * @param string $prefix
	 * @param object $options
	 * @param HandlerObject $handler
	 * 
	 * @return void
	 */
	public function __construct ($root, $prefix, $options, $handler) {
		#/Users/ut/haxe/haxe_libraries/tink_http_middleware/0.1.0/github/82c73bb5c4cd37a67f711b71a42e7ec2031d6894/src/tink/http/middleware/Static.hx:62: characters 3-19
		$this->root = $root;
		#/Users/ut/haxe/haxe_libraries/tink_http_middleware/0.1.0/github/82c73bb5c4cd37a67f711b71a42e7ec2031d6894/src/tink/http/middleware/Static.hx:63: characters 3-23
		$this->prefix = $prefix;
		#/Users/ut/haxe/haxe_libraries/tink_http_middleware/0.1.0/github/82c73bb5c4cd37a67f711b71a42e7ec2031d6894/src/tink/http/middleware/Static.hx:64: characters 3-25
		$this->options = $options;
		#/Users/ut/haxe/haxe_libraries/tink_http_middleware/0.1.0/github/82c73bb5c4cd37a67f711b71a42e7ec2031d6894/src/tink/http/middleware/Static.hx:65: characters 3-25
		$this->handler = $handler;
		#/Users/ut/haxe/haxe_libraries/tink_http_middleware/0.1.0/github/82c73bb5c4cd37a67f711b71a42e7ec2031d6894/src/tink/http/middleware/Static.hx:66: characters 3-51
		$this->notFound = new TypedError(404, "File Not Found", new HxAnon([
			"fileName" => "tink/http/middleware/Static.hx",
			"lineNumber" => 66,
			"className" => "tink.http.middleware.StaticHandler",
			"methodName" => "new",
		]));
	}

	/**
	 * @param Header $header
	 * @param object $stat
	 * @param StreamObject $source
	 * @param string $contentType
	 * @param string $filename
	 * 
	 * @return OutgoingResponseData
	 */
	public function partial ($header, $stat, $source, $contentType, $filename) {
		#/Users/ut/haxe/haxe_libraries/tink_http_middleware/0.1.0/github/82c73bb5c4cd37a67f711b71a42e7ec2031d6894/src/tink/http/middleware/Static.hx:101: characters 4-45
		$headers = new HeaderField(mb_strtolower("Accept-Ranges"), "bytes");
		#/Users/ut/haxe/haxe_libraries/tink_http_middleware/0.1.0/github/82c73bb5c4cd37a67f711b71a42e7ec2031d6894/src/tink/http/middleware/Static.hx:102: characters 4-46
		$headers1 = new HeaderField(mb_strtolower("Vary"), "Accept-Encoding");
		#/Users/ut/haxe/haxe_libraries/tink_http_middleware/0.1.0/github/82c73bb5c4cd37a67f711b71a42e7ec2031d6894/src/tink/http/middleware/Static.hx:103: characters 21-34
		$headers2 = mb_strtolower("Last-Modified");
		#/Users/ut/haxe/haxe_libraries/tink_http_middleware/0.1.0/github/82c73bb5c4cd37a67f711b71a42e7ec2031d6894/src/tink/http/middleware/Static.hx:103: characters 4-48
		$headers3 = new HeaderField($headers2, HeaderValue_Impl_::ofDate($stat->mtime));
		#/Users/ut/haxe/haxe_libraries/tink_http_middleware/0.1.0/github/82c73bb5c4cd37a67f711b71a42e7ec2031d6894/src/tink/http/middleware/Static.hx:104: characters 4-48
		$headers4 = new HeaderField(mb_strtolower("Content-Type"), $contentType);
		#/Users/ut/haxe/haxe_libraries/tink_http_middleware/0.1.0/github/82c73bb5c4cd37a67f711b71a42e7ec2031d6894/src/tink/http/middleware/Static.hx:100: lines 100-106
		$headers5 = \Array_hx::wrap([
			$headers,
			$headers1,
			$headers3,
			$headers4,
			new HeaderField(mb_strtolower("Content-Disposition"), "inline; filename=\"" . ($filename??'null') . "\""),
		]);
		#/Users/ut/haxe/haxe_libraries/tink_http_middleware/0.1.0/github/82c73bb5c4cd37a67f711b71a42e7ec2031d6894/src/tink/http/middleware/Static.hx:108: lines 108-111
		if (($this->options !== null) && ($this->options->expiry !== null)) {
			#/Users/ut/haxe/haxe_libraries/tink_http_middleware/0.1.0/github/82c73bb5c4cd37a67f711b71a42e7ec2031d6894/src/tink/http/middleware/Static.hx:109: characters 34-41
			$x = mb_strtolower("Expires");
			#/Users/ut/haxe/haxe_libraries/tink_http_middleware/0.1.0/github/82c73bb5c4cd37a67f711b71a42e7ec2031d6894/src/tink/http/middleware/Static.hx:109: characters 4-85
			$x1 = new HeaderField($x, HeaderValue_Impl_::ofDate(\Date::fromTime(\Date::now()->getTime() + $this->options->expiry * 1000)));
			$headers5->arr[$headers5->length] = $x1;
			++$headers5->length;

			#/Users/ut/haxe/haxe_libraries/tink_http_middleware/0.1.0/github/82c73bb5c4cd37a67f711b71a42e7ec2031d6894/src/tink/http/middleware/Static.hx:110: characters 34-47
			$x2 = mb_strtolower("Cache-Control");
			#/Users/ut/haxe/haxe_libraries/tink_http_middleware/0.1.0/github/82c73bb5c4cd37a67f711b71a42e7ec2031d6894/src/tink/http/middleware/Static.hx:110: characters 4-79
			$headers5->arr[$headers5->length] = new HeaderField($x2, "max-age=" . ($this->options->expiry??'null'));
			++$headers5->length;

		}
		#/Users/ut/haxe/haxe_libraries/tink_http_middleware/0.1.0/github/82c73bb5c4cd37a67f711b71a42e7ec2031d6894/src/tink/http/middleware/Static.hx:114: characters 10-32
		$_g = $header->byName(mb_strtolower("range"));
		$__hx__switch = ($_g->index);
		if ($__hx__switch === 0) {
			#/Users/ut/haxe/haxe_libraries/tink_http_middleware/0.1.0/github/82c73bb5c4cd37a67f711b71a42e7ec2031d6894/src/tink/http/middleware/Static.hx:115: characters 17-18
			$v = $_g->params[0];
			#/Users/ut/haxe/haxe_libraries/tink_http_middleware/0.1.0/github/82c73bb5c4cd37a67f711b71a42e7ec2031d6894/src/tink/http/middleware/Static.hx:116: characters 12-33
			$_g1 = HxString::split($v, "=");
			if (($_g1->length === 2) && (($_g1->arr[0] ?? null) === "bytes")) {
				#/Users/ut/haxe/haxe_libraries/tink_http_middleware/0.1.0/github/82c73bb5c4cd37a67f711b71a42e7ec2031d6894/src/tink/http/middleware/Static.hx:117: characters 21-26
				$range = ($_g1->arr[1] ?? null);
				#/Users/ut/haxe/haxe_libraries/tink_http_middleware/0.1.0/github/82c73bb5c4cd37a67f711b71a42e7ec2031d6894/src/tink/http/middleware/Static.hx:118: lines 118-126
				$res = function ($pos, $len)  use (&$source, &$stat, &$headers5) {
					#/Users/ut/haxe/haxe_libraries/tink_http_middleware/0.1.0/github/82c73bb5c4cd37a67f711b71a42e7ec2031d6894/src/tink/http/middleware/Static.hx:121: characters 27-40
					$fields = mb_strtolower("Content-Range");
					#/Users/ut/haxe/haxe_libraries/tink_http_middleware/0.1.0/github/82c73bb5c4cd37a67f711b71a42e7ec2031d6894/src/tink/http/middleware/Static.hx:121: characters 10-86
					$fields1 = new HeaderField($fields, "bytes " . ($pos??'null') . "-" . (($pos + $len - 1)??'null') . "/" . ($stat->size??'null'));
					#/Users/ut/haxe/haxe_libraries/tink_http_middleware/0.1.0/github/82c73bb5c4cd37a67f711b71a42e7ec2031d6894/src/tink/http/middleware/Static.hx:122: characters 27-41
					$fields2 = mb_strtolower("Content-Length");
					#/Users/ut/haxe/haxe_libraries/tink_http_middleware/0.1.0/github/82c73bb5c4cd37a67f711b71a42e7ec2031d6894/src/tink/http/middleware/Static.hx:120: lines 120-123
					$this1 = new ResponseHeaderBase(206, "Partial Content", $headers5->concat(\Array_hx::wrap([
						$fields1,
						new HeaderField($fields2, HeaderValue_Impl_::ofInt($len)),
					])), "HTTP/1.1");
					#/Users/ut/haxe/haxe_libraries/tink_http_middleware/0.1.0/github/82c73bb5c4cd37a67f711b71a42e7ec2031d6894/src/tink/http/middleware/Static.hx:119: lines 119-125
					$this2 = new OutgoingResponseData($this1, Source_Impl_::limit(Source_Impl_::skip($source, $pos), $len));
					return $this2;
				};
				#/Users/ut/haxe/haxe_libraries/tink_http_middleware/0.1.0/github/82c73bb5c4cd37a67f711b71a42e7ec2031d6894/src/tink/http/middleware/Static.hx:128: characters 14-30
				$_g2 = HxString::split($range, "-");
				if ($_g2->length === 2) {
					#/Users/ut/haxe/haxe_libraries/tink_http_middleware/0.1.0/github/82c73bb5c4cd37a67f711b71a42e7ec2031d6894/src/tink/http/middleware/Static.hx:131: characters 14-29
					$_hx_tmp = null;
					#/Users/ut/haxe/haxe_libraries/tink_http_middleware/0.1.0/github/82c73bb5c4cd37a67f711b71a42e7ec2031d6894/src/tink/http/middleware/Static.hx:128: characters 14-30
					if (($_g2->arr[0] ?? null) === "") {
						#/Users/ut/haxe/haxe_libraries/tink_http_middleware/0.1.0/github/82c73bb5c4cd37a67f711b71a42e7ec2031d6894/src/tink/http/middleware/Static.hx:131: characters 14-29
						$_hx_tmp = \Std::parseInt(($_g2->arr[0] ?? null));
						#/Users/ut/haxe/haxe_libraries/tink_http_middleware/0.1.0/github/82c73bb5c4cd37a67f711b71a42e7ec2031d6894/src/tink/http/middleware/Static.hx:129: lines 129-130
						if ($_hx_tmp === null) {
							if ($_hx_tmp === null) {
								#/Users/ut/haxe/haxe_libraries/tink_http_middleware/0.1.0/github/82c73bb5c4cd37a67f711b71a42e7ec2031d6894/src/tink/http/middleware/Static.hx:129: characters 18-33
								$_hx_tmp1 = \Std::parseInt(($_g2->arr[1] ?? null));
								#/Users/ut/haxe/haxe_libraries/tink_http_middleware/0.1.0/github/82c73bb5c4cd37a67f711b71a42e7ec2031d6894/src/tink/http/middleware/Static.hx:130: characters 9-41
								return $res($stat->size - $_hx_tmp1, $_hx_tmp1);
							} else {
								#/Users/ut/haxe/haxe_libraries/tink_http_middleware/0.1.0/github/82c73bb5c4cd37a67f711b71a42e7ec2031d6894/src/tink/http/middleware/Static.hx:129: characters 18-33
								$_hx_tmp2 = \Std::parseInt(($_g2->arr[1] ?? null));
								#/Users/ut/haxe/haxe_libraries/tink_http_middleware/0.1.0/github/82c73bb5c4cd37a67f711b71a42e7ec2031d6894/src/tink/http/middleware/Static.hx:130: characters 9-41
								return $res($stat->size - $_hx_tmp2, $_hx_tmp2);
							}
						} else if ($_hx_tmp === null) {
							#/Users/ut/haxe/haxe_libraries/tink_http_middleware/0.1.0/github/82c73bb5c4cd37a67f711b71a42e7ec2031d6894/src/tink/http/middleware/Static.hx:129: characters 18-33
							$_hx_tmp3 = \Std::parseInt(($_g2->arr[1] ?? null));
							#/Users/ut/haxe/haxe_libraries/tink_http_middleware/0.1.0/github/82c73bb5c4cd37a67f711b71a42e7ec2031d6894/src/tink/http/middleware/Static.hx:130: characters 9-41
							return $res($stat->size - $_hx_tmp3, $_hx_tmp3);
						} else {
							#/Users/ut/haxe/haxe_libraries/tink_http_middleware/0.1.0/github/82c73bb5c4cd37a67f711b71a42e7ec2031d6894/src/tink/http/middleware/Static.hx:129: characters 18-33
							$_hx_tmp4 = \Std::parseInt(($_g2->arr[1] ?? null));
							#/Users/ut/haxe/haxe_libraries/tink_http_middleware/0.1.0/github/82c73bb5c4cd37a67f711b71a42e7ec2031d6894/src/tink/http/middleware/Static.hx:130: characters 9-41
							return $res($stat->size - $_hx_tmp4, $_hx_tmp4);
						}
					} else {
						#/Users/ut/haxe/haxe_libraries/tink_http_middleware/0.1.0/github/82c73bb5c4cd37a67f711b71a42e7ec2031d6894/src/tink/http/middleware/Static.hx:133: characters 38-53
						$_hx_tmp5 = null;
						#/Users/ut/haxe/haxe_libraries/tink_http_middleware/0.1.0/github/82c73bb5c4cd37a67f711b71a42e7ec2031d6894/src/tink/http/middleware/Static.hx:128: characters 14-30
						if (($_g2->arr[1] ?? null) === "") {
							#/Users/ut/haxe/haxe_libraries/tink_http_middleware/0.1.0/github/82c73bb5c4cd37a67f711b71a42e7ec2031d6894/src/tink/http/middleware/Static.hx:131: characters 14-29
							$_hx_tmp = \Std::parseInt(($_g2->arr[0] ?? null));
							#/Users/ut/haxe/haxe_libraries/tink_http_middleware/0.1.0/github/82c73bb5c4cd37a67f711b71a42e7ec2031d6894/src/tink/http/middleware/Static.hx:131: characters 33-36
							$pos1 = $_hx_tmp;
							#/Users/ut/haxe/haxe_libraries/tink_http_middleware/0.1.0/github/82c73bb5c4cd37a67f711b71a42e7ec2031d6894/src/tink/http/middleware/Static.hx:132: characters 9-41
							return $res($pos1, $stat->size - $pos1);
						} else {
							#/Users/ut/haxe/haxe_libraries/tink_http_middleware/0.1.0/github/82c73bb5c4cd37a67f711b71a42e7ec2031d6894/src/tink/http/middleware/Static.hx:131: characters 14-29
							$_hx_tmp = \Std::parseInt(($_g2->arr[0] ?? null));
							#/Users/ut/haxe/haxe_libraries/tink_http_middleware/0.1.0/github/82c73bb5c4cd37a67f711b71a42e7ec2031d6894/src/tink/http/middleware/Static.hx:133: characters 33-36
							$pos2 = $_hx_tmp;
							#/Users/ut/haxe/haxe_libraries/tink_http_middleware/0.1.0/github/82c73bb5c4cd37a67f711b71a42e7ec2031d6894/src/tink/http/middleware/Static.hx:133: characters 38-53
							$_hx_tmp5 = \Std::parseInt(($_g2->arr[1] ?? null));
							#/Users/ut/haxe/haxe_libraries/tink_http_middleware/0.1.0/github/82c73bb5c4cd37a67f711b71a42e7ec2031d6894/src/tink/http/middleware/Static.hx:134: characters 9-39
							return $res($pos2, $_hx_tmp5 - $pos2 + 1);
						}
					}
				}


			}

		} else if ($__hx__switch === 1) {
		}

		#/Users/ut/haxe/haxe_libraries/tink_http_middleware/0.1.0/github/82c73bb5c4cd37a67f711b71a42e7ec2031d6894/src/tink/http/middleware/Static.hx:144: characters 22-36
		$fields3 = mb_strtolower("Content-Length");
		#/Users/ut/haxe/haxe_libraries/tink_http_middleware/0.1.0/github/82c73bb5c4cd37a67f711b71a42e7ec2031d6894/src/tink/http/middleware/Static.hx:143: lines 143-145
		$this3 = new ResponseHeaderBase(200, "OK", $headers5->concat(\Array_hx::wrap([new HeaderField($fields3, HeaderValue_Impl_::ofInt($stat->size))])), "HTTP/1.1");
		#/Users/ut/haxe/haxe_libraries/tink_http_middleware/0.1.0/github/82c73bb5c4cd37a67f711b71a42e7ec2031d6894/src/tink/http/middleware/Static.hx:142: lines 142-147
		$this4 = new OutgoingResponseData($this3, $source);
		return $this4;
	}

	/**
	 * @param IncomingRequest $req
	 * 
	 * @return FutureObject
	 */
	public function process ($req) {
		#/Users/ut/haxe/haxe_libraries/tink_http_middleware/0.1.0/github/82c73bb5c4cd37a67f711b71a42e7ec2031d6894/src/tink/http/middleware/Static.hx:69: lines 69-96
		$_gthis = $this;
		#/Users/ut/haxe/haxe_libraries/tink_http_middleware/0.1.0/github/82c73bb5c4cd37a67f711b71a42e7ec2031d6894/src/tink/http/middleware/Static.hx:70: characters 3-41
		$path = $req->header->url->path;
		#/Users/ut/haxe/haxe_libraries/tink_http_middleware/0.1.0/github/82c73bb5c4cd37a67f711b71a42e7ec2031d6894/src/tink/http/middleware/Static.hx:71: lines 71-93
		if (($req->header->method === "GET") && \StringTools::startsWith($path, $this->prefix)) {
			#/Users/ut/haxe/haxe_libraries/tink_http_middleware/0.1.0/github/82c73bb5c4cd37a67f711b71a42e7ec2031d6894/src/tink/http/middleware/Static.hx:72: characters 32-36
			$staticPath = $this->root;
			#/Users/ut/haxe/haxe_libraries/tink_http_middleware/0.1.0/github/82c73bb5c4cd37a67f711b71a42e7ec2031d6894/src/tink/http/middleware/Static.hx:72: characters 4-79
			$staticPath1 = Path::join(\Array_hx::wrap([
				$staticPath,
				urldecode(mb_substr($path, mb_strlen($this->prefix), null)),
			]));
			#/Users/ut/haxe/haxe_libraries/tink_http_middleware/0.1.0/github/82c73bb5c4cd37a67f711b71a42e7ec2031d6894/src/tink/http/middleware/Static.hx:74: lines 74-80
			$result = Promise_Impl_::next(Promise_Impl_::next(Future_Impl_::next(FileSystem::exists($staticPath1), function ($exists)  use (&$_gthis, &$staticPath1) {
				#/Users/ut/haxe/haxe_libraries/tink_http_middleware/0.1.0/github/82c73bb5c4cd37a67f711b71a42e7ec2031d6894/src/tink/http/middleware/Static.hx:75: characters 36-96
				if (!$exists) {
					#/Users/ut/haxe/haxe_libraries/tink_http_middleware/0.1.0/github/82c73bb5c4cd37a67f711b71a42e7ec2031d6894/src/tink/http/middleware/Static.hx:75: characters 48-56
					return new SyncFuture(new LazyConst(Outcome::Failure($_gthis->notFound)));
				} else {
					#/Users/ut/haxe/haxe_libraries/tink_http_middleware/0.1.0/github/82c73bb5c4cd37a67f711b71a42e7ec2031d6894/src/tink/http/middleware/Static.hx:75: characters 62-96
					$ret = FileSystem::isDirectory($staticPath1)->map(Boot::getStaticClosure(Outcome::class, 'Success'));
					return $ret->gather();
				}
			}), function ($isDir)  use (&$_gthis, &$staticPath1) {
				#/Users/ut/haxe/haxe_libraries/tink_http_middleware/0.1.0/github/82c73bb5c4cd37a67f711b71a42e7ec2031d6894/src/tink/http/middleware/Static.hx:76: characters 35-86
				if ($isDir) {
					#/Users/ut/haxe/haxe_libraries/tink_http_middleware/0.1.0/github/82c73bb5c4cd37a67f711b71a42e7ec2031d6894/src/tink/http/middleware/Static.hx:76: characters 45-53
					return new SyncFuture(new LazyConst(Outcome::Failure($_gthis->notFound)));
				} else {
					#/Users/ut/haxe/haxe_libraries/tink_http_middleware/0.1.0/github/82c73bb5c4cd37a67f711b71a42e7ec2031d6894/src/tink/http/middleware/Static.hx:76: characters 59-86
					return FileSystem::stat($staticPath1);
				}
			}), function ($stat)  use (&$req, &$_gthis, &$staticPath1) {
				#/Users/ut/haxe/haxe_libraries/tink_http_middleware/0.1.0/github/82c73bb5c4cd37a67f711b71a42e7ec2031d6894/src/tink/http/middleware/Static.hx:78: characters 7-47
				$mime1 = Mime::lookup($staticPath1);
				#/Users/ut/haxe/haxe_libraries/tink_http_middleware/0.1.0/github/82c73bb5c4cd37a67f711b71a42e7ec2031d6894/src/tink/http/middleware/Static.hx:79: characters 22-32
				$req1 = $req->header;
				#/Users/ut/haxe/haxe_libraries/tink_http_middleware/0.1.0/github/82c73bb5c4cd37a67f711b71a42e7ec2031d6894/src/tink/http/middleware/Static.hx:79: characters 40-109
				$d = RealSourceTools::idealize(File::readStream($staticPath1), function ($_) {
					#/Users/ut/haxe/haxe_libraries/tink_http_middleware/0.1.0/github/82c73bb5c4cd37a67f711b71a42e7ec2031d6894/src/tink/http/middleware/Static.hx:79: characters 89-108
					return Source_Impl_::$EMPTY;
				});
				#/Users/ut/haxe/haxe_libraries/tink_http_middleware/0.1.0/github/82c73bb5c4cd37a67f711b71a42e7ec2031d6894/src/tink/http/middleware/Static.hx:79: characters 117-146
				$d1 = Path::withoutDirectory($staticPath1);
				#/Users/ut/haxe/haxe_libraries/tink_http_middleware/0.1.0/github/82c73bb5c4cd37a67f711b71a42e7ec2031d6894/src/tink/http/middleware/Static.hx:79: characters 7-147
				return new SyncFuture(new LazyConst(Outcome::Success($_gthis->partial($req1, $stat, $d, $mime1, $d1))));
			});
			#/Users/ut/haxe/haxe_libraries/tink_http_middleware/0.1.0/github/82c73bb5c4cd37a67f711b71a42e7ec2031d6894/src/tink/http/middleware/Static.hx:82: characters 12-67
			$f = function ($_1)  use (&$req, &$_gthis) {
				#/Users/ut/haxe/haxe_libraries/tink_http_middleware/0.1.0/github/82c73bb5c4cd37a67f711b71a42e7ec2031d6894/src/tink/http/middleware/Static.hx:82: characters 39-66
				return $_gthis->handler->process($req);
			};
			#/Users/ut/haxe/haxe_libraries/tink_http_middleware/0.1.0/github/82c73bb5c4cd37a67f711b71a42e7ec2031d6894/src/tink/http/middleware/Static.hx:82: characters 12-67
			$ret1 = $result->flatMap(function ($o)  use (&$f) {
				$__hx__switch = ($o->index);
				if ($__hx__switch === 0) {
					$d2 = $o->params[0];
					return new SyncFuture(new LazyConst($d2));
				} else if ($__hx__switch === 1) {
					$e = $o->params[0];
					return $f($e);
				}
			});
			return $ret1->gather();
		}
		#/Users/ut/haxe/haxe_libraries/tink_http_middleware/0.1.0/github/82c73bb5c4cd37a67f711b71a42e7ec2031d6894/src/tink/http/middleware/Static.hx:95: characters 3-30
		return $this->handler->process($req);
	}
}

Boot::registerClass(StaticHandler::class, 'tink.http.middleware.StaticHandler');
