<?php
/**
 * Generated by Haxe 4.0.0-rc.2+77068e1
 * Haxe source file: /Users/ut/haxe/haxe_libraries/tink_querystring/0.6.0/haxelib/src/tink/querystring/Parser.hx
 */

namespace tink\querystring;

use \php\Boot;

class Parser {
}

Boot::registerClass(Parser::class, 'tink.querystring.Parser');
