<?php
/**
 * Generated by Haxe 4.0.0-rc.1+1fdd3d5
 * Haxe source file: /Users/ut/haxe/haxe_libraries/tink_sql/0.0.0-alpha.0/github/485516a0ac3307cf25ff126f4feafff93a01878a/src/tink/sql/Database.hx
 */

namespace tink\sql;

use \php\_Boot\HxAnon;
use \php\Boot;
use \tink\core\TypedError;
use \haxe\ds\StringMap;
use \php\_Boot\HxException;
use \php\_NativeIndexedArray\NativeIndexedArrayIterator;

class Database implements DatabaseInfo {
	/**
	 * @var Driver
	 */
	public $driver;
	/**
	 * @var string
	 */
	public $name;
	/**
	 * @var StringMap
	 */
	public $tables;

	/**
	 * @param string $name
	 * @param Driver $driver
	 * @param StringMap $tables
	 * 
	 * @return void
	 */
	public function __construct ($name, $driver, $tables) {
		#/Users/ut/haxe/haxe_libraries/tink_sql/0.0.0-alpha.0/github/485516a0ac3307cf25ff126f4feafff93a01878a/src/tink/sql/Database.hx:15: characters 5-21
		$this->name = $name;
		#/Users/ut/haxe/haxe_libraries/tink_sql/0.0.0-alpha.0/github/485516a0ac3307cf25ff126f4feafff93a01878a/src/tink/sql/Database.hx:16: characters 5-25
		$this->driver = $driver;
		#/Users/ut/haxe/haxe_libraries/tink_sql/0.0.0-alpha.0/github/485516a0ac3307cf25ff126f4feafff93a01878a/src/tink/sql/Database.hx:17: characters 5-25
		$this->tables = $tables;
	}

	/**
	 * @param string $name
	 * 
	 * @return TableInfo
	 */
	public function tableInfo ($name) {
		#/Users/ut/haxe/haxe_libraries/tink_sql/0.0.0-alpha.0/github/485516a0ac3307cf25ff126f4feafff93a01878a/src/tink/sql/Database.hx:26: characters 19-31
		$_g = ($this->tables->data[$name] ?? null);
		#/Users/ut/haxe/haxe_libraries/tink_sql/0.0.0-alpha.0/github/485516a0ac3307cf25ff126f4feafff93a01878a/src/tink/sql/Database.hx:27: lines 27-28
		if ($_g === null) {
			#/Users/ut/haxe/haxe_libraries/tink_sql/0.0.0-alpha.0/github/485516a0ac3307cf25ff126f4feafff93a01878a/src/tink/sql/Database.hx:27: characters 18-23
			throw new HxException(new TypedError(404, "Table `" . ($this->name??'null') . "." . ($name??'null') . "` not found", new HxAnon([
				"fileName" => "tink/sql/Database.hx",
				"lineNumber" => 27,
				"className" => "tink.sql.Database",
				"methodName" => "tableInfo",
			])));
		} else {
			#/Users/ut/haxe/haxe_libraries/tink_sql/0.0.0-alpha.0/github/485516a0ac3307cf25ff126f4feafff93a01878a/src/tink/sql/Database.hx:28: characters 15-21
			return $_g;
		}
	}

	/**
	 * @return object
	 */
	public function tableNames () {
		#/Users/ut/haxe/haxe_libraries/tink_sql/0.0.0-alpha.0/github/485516a0ac3307cf25ff126f4feafff93a01878a/src/tink/sql/Database.hx:20: lines 20-23
		$_gthis = $this;
		#/Users/ut/haxe/haxe_libraries/tink_sql/0.0.0-alpha.0/github/485516a0ac3307cf25ff126f4feafff93a01878a/src/tink/sql/Database.hx:21: lines 21-23
		return new HxAnon(["iterator" => function ()  use (&$_gthis) {
			#/Users/ut/haxe/haxe_libraries/tink_sql/0.0.0-alpha.0/github/485516a0ac3307cf25ff126f4feafff93a01878a/src/tink/sql/Database.hx:22: characters 36-49
			return new NativeIndexedArrayIterator(array_map("strval", array_keys($_gthis->tables->data)));
		}]);
	}
}

Boot::registerClass(Database::class, 'tink.sql.Database');
