<?php
/**
 * Generated by Haxe 4.0.0-rc.1+1fdd3d5
 * Haxe source file: /Users/ut/haxe/haxe_libraries/tink_sql/0.0.0-alpha.0/github/485516a0ac3307cf25ff126f4feafff93a01878a/src/tink/sql/Dataset.hx
 */

namespace tink\sql;

use \php\_Boot\HxAnon;
use \php\Boot;
use \tink\sql\_Expr\Expr_Impl_;

class FilterableHaving extends Orderable {
	/**
	 * @param Connection $cnx
	 * @param mixed $fields
	 * @param Target $target
	 * @param \Closure $toCondition
	 * @param object $condition
	 * @param mixed $selection
	 * @param \Array_hx $grouped
	 * @param \Array_hx $order
	 * 
	 * @return void
	 */
	public function __construct ($cnx, $fields, $target, $toCondition, $condition = null, $selection = null, $grouped = null, $order = null) {
		#/Users/ut/haxe/haxe_libraries/tink_sql/0.0.0-alpha.0/github/485516a0ac3307cf25ff126f4feafff93a01878a/src/tink/sql/Dataset.hx:50: lines 50-63
		parent::__construct($cnx, $fields, $target, $toCondition, $condition, $selection, $grouped, $order);
	}

	/**
	 * @param mixed $filter
	 * 
	 * @return FilterableHaving
	 */
	public function _having ($filter) {
		#/Users/ut/haxe/haxe_libraries/tink_sql/0.0.0-alpha.0/github/485516a0ac3307cf25ff126f4feafff93a01878a/src/tink/sql/Dataset.hx:58: characters 33-36
		$tmp = $this->cnx;
		#/Users/ut/haxe/haxe_libraries/tink_sql/0.0.0-alpha.0/github/485516a0ac3307cf25ff126f4feafff93a01878a/src/tink/sql/Dataset.hx:58: characters 38-44
		$tmp1 = $this->fields;
		#/Users/ut/haxe/haxe_libraries/tink_sql/0.0.0-alpha.0/github/485516a0ac3307cf25ff126f4feafff93a01878a/src/tink/sql/Dataset.hx:58: characters 46-52
		$tmp2 = $this->target;
		#/Users/ut/haxe/haxe_libraries/tink_sql/0.0.0-alpha.0/github/485516a0ac3307cf25ff126f4feafff93a01878a/src/tink/sql/Dataset.hx:58: characters 54-65
		$tmp3 = $this->toCondition;
		#/Users/ut/haxe/haxe_libraries/tink_sql/0.0.0-alpha.0/github/485516a0ac3307cf25ff126f4feafff93a01878a/src/tink/sql/Dataset.hx:59: characters 14-29
		$tmp4 = $this->condition->where;
		#/Users/ut/haxe/haxe_libraries/tink_sql/0.0.0-alpha.0/github/485516a0ac3307cf25ff126f4feafff93a01878a/src/tink/sql/Dataset.hx:60: characters 15-31
		$tmp5 = $this->condition->having;
		#/Users/ut/haxe/haxe_libraries/tink_sql/0.0.0-alpha.0/github/485516a0ac3307cf25ff126f4feafff93a01878a/src/tink/sql/Dataset.hx:60: characters 35-54
		$tmp6 = ($this->toCondition)($filter);
		#/Users/ut/haxe/haxe_libraries/tink_sql/0.0.0-alpha.0/github/485516a0ac3307cf25ff126f4feafff93a01878a/src/tink/sql/Dataset.hx:58: lines 58-61
		return new FilterableHaving($tmp, $tmp1, $tmp2, $tmp3, new HxAnon([
			"where" => $tmp4,
			"having" => Expr_Impl_::and($tmp5, $tmp6),
		]), $this->selection);
	}
}

Boot::registerClass(FilterableHaving::class, 'tink.sql.FilterableHaving');
