<?php
/**
 * Generated by Haxe 4.0.0-rc.1+1fdd3d5
 * Haxe source file: /Users/ut/haxe/haxe_libraries/tink_sql/0.0.0-alpha.0/github/485516a0ac3307cf25ff126f4feafff93a01878a/src/tink/sql/Info.hx
 */

namespace tink\sql;

use \php\Boot;
use \php\_Boot\HxEnum;

class IntSize extends HxEnum {
	/**
	 * @return IntSize
	 */
	static public function Default () {
		static $inst = null;
		if (!$inst) $inst = new IntSize('Default', 3, []);
		return $inst;
	}

	/**
	 * @return IntSize
	 */
	static public function Medium () {
		static $inst = null;
		if (!$inst) $inst = new IntSize('Medium', 2, []);
		return $inst;
	}

	/**
	 * @return IntSize
	 */
	static public function Small () {
		static $inst = null;
		if (!$inst) $inst = new IntSize('Small', 1, []);
		return $inst;
	}

	/**
	 * @return IntSize
	 */
	static public function Tiny () {
		static $inst = null;
		if (!$inst) $inst = new IntSize('Tiny', 0, []);
		return $inst;
	}

	/**
	 * Returns array of (constructorIndex => constructorName)
	 *
	 * @return string[]
	 */
	static public function __hx__list () {
		return [
			3 => 'Default',
			2 => 'Medium',
			1 => 'Small',
			0 => 'Tiny',
		];
	}

	/**
	 * Returns array of (constructorName => parametersCount)
	 *
	 * @return int[]
	 */
	static public function __hx__paramsCount () {
		return [
			'Default' => 0,
			'Medium' => 0,
			'Small' => 0,
			'Tiny' => 0,
		];
	}
}

Boot::registerClass(IntSize::class, 'tink.sql.IntSize');
