<?php
/**
 * Generated by Haxe 4.0.0-rc.1+1fdd3d5
 * Haxe source file: /Users/ut/haxe/haxe_libraries/tink_sql/0.0.0-alpha.0/github/485516a0ac3307cf25ff126f4feafff93a01878a/src/tink/sql/Query.hx
 */

namespace tink\sql;

use \php\Boot;
use \php\_Boot\HxEnum;

class Query extends HxEnum {
	/**
	 * @param TableInfo $table
	 * @param \Array_hx $changes
	 * 
	 * @return Query
	 */
	static public function AlterTable ($table, $changes) {
		return new Query('AlterTable', 7, [$table, $changes]);
	}

	/**
	 * @param TableInfo $table
	 * @param bool $ifNotExists
	 * 
	 * @return Query
	 */
	static public function CreateTable ($table, $ifNotExists = null) {
		return new Query('CreateTable', 5, [$table, $ifNotExists]);
	}

	/**
	 * @param object $delete
	 * 
	 * @return Query
	 */
	static public function Delete ($delete) {
		return new Query('Delete', 4, [$delete]);
	}

	/**
	 * @param TableInfo $table
	 * 
	 * @return Query
	 */
	static public function DropTable ($table) {
		return new Query('DropTable', 6, [$table]);
	}

	/**
	 * @param object $insert
	 * 
	 * @return Query
	 */
	static public function Insert ($insert) {
		return new Query('Insert', 2, [$insert]);
	}

	/**
	 * @param object $select
	 * 
	 * @return Query
	 */
	static public function Select ($select) {
		return new Query('Select', 1, [$select]);
	}

	/**
	 * @param TableInfo $from
	 * 
	 * @return Query
	 */
	static public function ShowColumns ($from) {
		return new Query('ShowColumns', 8, [$from]);
	}

	/**
	 * @param TableInfo $from
	 * 
	 * @return Query
	 */
	static public function ShowIndex ($from) {
		return new Query('ShowIndex', 9, [$from]);
	}

	/**
	 * @param object $union
	 * 
	 * @return Query
	 */
	static public function Union ($union) {
		return new Query('Union', 0, [$union]);
	}

	/**
	 * @param object $update
	 * 
	 * @return Query
	 */
	static public function Update ($update) {
		return new Query('Update', 3, [$update]);
	}

	/**
	 * Returns array of (constructorIndex => constructorName)
	 *
	 * @return string[]
	 */
	static public function __hx__list () {
		return [
			7 => 'AlterTable',
			5 => 'CreateTable',
			4 => 'Delete',
			6 => 'DropTable',
			2 => 'Insert',
			1 => 'Select',
			8 => 'ShowColumns',
			9 => 'ShowIndex',
			0 => 'Union',
			3 => 'Update',
		];
	}

	/**
	 * Returns array of (constructorName => parametersCount)
	 *
	 * @return int[]
	 */
	static public function __hx__paramsCount () {
		return [
			'AlterTable' => 2,
			'CreateTable' => 2,
			'Delete' => 1,
			'DropTable' => 1,
			'Insert' => 1,
			'Select' => 1,
			'ShowColumns' => 1,
			'ShowIndex' => 1,
			'Union' => 1,
			'Update' => 1,
		];
	}
}

Boot::registerClass(Query::class, 'tink.sql.Query');
