<?php
/**
 * Generated by Haxe 4.0.0-rc.1+1fdd3d5
 * Haxe source file: /Users/ut/haxe/haxe_libraries/tink_sql/0.0.0-alpha.0/github/485516a0ac3307cf25ff126f4feafff93a01878a/src/tink/sql/Target.hx
 */

namespace tink\sql;

use \php\Boot;
use \php\_Boot\HxEnum;

class Target extends HxEnum {
	/**
	 * @param Target $left
	 * @param Target $right
	 * @param string $type
	 * @param ExprData $c
	 * 
	 * @return Target
	 */
	static public function TJoin ($left, $right, $type, $c) {
		return new Target('TJoin', 1, [$left, $right, $type, $c]);
	}

	/**
	 * @param string $name
	 * @param string $alias
	 * 
	 * @return Target
	 */
	static public function TTable ($name, $alias = null) {
		return new Target('TTable', 0, [$name, $alias]);
	}

	/**
	 * Returns array of (constructorIndex => constructorName)
	 *
	 * @return string[]
	 */
	static public function __hx__list () {
		return [
			1 => 'TJoin',
			0 => 'TTable',
		];
	}

	/**
	 * Returns array of (constructorName => parametersCount)
	 *
	 * @return int[]
	 */
	static public function __hx__paramsCount () {
		return [
			'TJoin' => 4,
			'TTable' => 2,
		];
	}
}

Boot::registerClass(Target::class, 'tink.sql.Target');
