<?php
/**
 * Generated by Haxe 4.0.0-rc.2+77068e1
 * Haxe source file: /Users/ut/haxe/haxe_libraries/tink_url/0.4.1/haxelib/src/tink/url/PortionArray.hx
 */

namespace tink\url\_PortionArray;

use \php\Boot;
use \tink\url\_Portion\Portion_Impl_;

final class PortionArray_Impl_ {
	/**
	 * @param \Array_hx $this
	 * 
	 * @return \Array_hx
	 */
	static public function toStringArray ($this1) {
		#/Users/ut/haxe/haxe_libraries/tink_url/0.4.1/haxelib/src/tink/url/PortionArray.hx:7: characters 10-39
		$_g = new \Array_hx();
		#/Users/ut/haxe/haxe_libraries/tink_url/0.4.1/haxelib/src/tink/url/PortionArray.hx:7: characters 11-38
		$_g1 = 0;
		while ($_g1 < $this1->length) {
			#/Users/ut/haxe/haxe_libraries/tink_url/0.4.1/haxelib/src/tink/url/PortionArray.hx:7: characters 15-16
			$p = ($this1->arr[$_g1] ?? null);
			#/Users/ut/haxe/haxe_libraries/tink_url/0.4.1/haxelib/src/tink/url/PortionArray.hx:7: characters 11-38
			++$_g1;
			#/Users/ut/haxe/haxe_libraries/tink_url/0.4.1/haxelib/src/tink/url/PortionArray.hx:7: characters 26-38
			$x = Portion_Impl_::toString($p);
			$_g->arr[$_g->length] = $x;
			++$_g->length;

		}

		#/Users/ut/haxe/haxe_libraries/tink_url/0.4.1/haxelib/src/tink/url/PortionArray.hx:7: characters 10-39
		return $_g;
	}
}

Boot::registerClass(PortionArray_Impl_::class, 'tink.url._PortionArray.PortionArray_Impl_');
