<?php
/**
 * Generated by Haxe 4.0.0-rc.2+77068e1
 * Haxe source file: src/wire/ICommand.hx
 */

namespace wire;

use \php\Boot;

interface ICommand {
	/**
	 * @param mixed $data
	 * 
	 * @return void
	 */
	public function execute ($data = null) ;
}

Boot::registerClass(ICommand::class, 'wire.ICommand');
