<?php
/**
 * Generated by Haxe 4.0.0-rc.1+1fdd3d5
 * Haxe source file: /Users/ut/haxe/haxe_libraries/tink_sql/0.0.0-alpha.0/github/485516a0ac3307cf25ff126f4feafff93a01878a/src/tink/sql/Table.hx
 */

namespace tink\sql\_Table;

use \php\Boot;

final class TableName_Impl_ {
	/**
	 * @param string $s
	 * 
	 * @return string
	 */
	static public function _new ($s) {
		#/Users/ut/haxe/haxe_libraries/tink_sql/0.0.0-alpha.0/github/485516a0ac3307cf25ff126f4feafff93a01878a/src/tink/sql/Table.hx:166: character 3
		return $s;
	}
}

Boot::registerClass(TableName_Impl_::class, 'tink.sql._Table.TableName_Impl_');
