<?php
/**
 * Generated by Haxe 4.0.0-rc.2+77068e1
 * Haxe source file: /Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx
 */

namespace image;

use \php\_Boot\HxAnon;
use \tink\core\_Future\SyncFuture;
use \php\Boot;
use \tink\core\Noise;
use \tink\core\TypedError;
use \asys\io\Process;
use \sys\io\FileSeek;
use \asys\io\File;
use \tink\core\Outcome;
use \tink\core\_Lazy\LazyConst;
use \tink\core\_Future\Future_Impl_;
use \asys\FileSystem;
use \php\_Boot\HxException;
use \haxe\io\Bytes;
use \haxe\io\Path;
use \tink\core\_Future\FutureObject;

class Image {
	/**
	 * @param string $path
	 * 
	 * @return FutureObject
	 */
	static public function getInfo ($path) {
		#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:252: lines 252-256
		$width = 0;
		$height = 0;
		$format = null;
		$unsupported = "Unsupported image format";
		#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:259: lines 259-361
		$ret = File::read($path)->map(function ($res)  use (&$width, &$height, &$format, &$unsupported) {
			#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:260: lines 260-361
			$__hx__switch = ($res->index);
			if ($__hx__switch === 0) {
				#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:261: characters 17-22
				$input = $res->params[0];
				#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:262: characters 12-30
				$_g = $input->readUInt16();
				if ($_g === 18759) {
					#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:281: lines 281-348
					if (($_g === 18761) || ($_g === 19789)) {
						#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:282: characters 7-41
						$input->set_bigEndian($_g === 19789);
						#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:283: lines 283-284
						if ($input->readUInt16() !== 42) {
							#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:284: characters 8-46
							return Outcome::Failure(new TypedError(null, $unsupported, new HxAnon([
								"fileName" => "image/Image.hx",
								"lineNumber" => 284,
								"className" => "image.Image",
								"methodName" => "getInfo",
							])));
						}
						#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:285: characters 7-32
						$format = "tiff";
						#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:286: characters 7-38
						$offset = $input->readInt32();
						#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:287: characters 7-45
						$input->seek($offset, FileSeek::SeekBegin());
						#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:288: characters 7-38
						$count = $input->readUInt16();
						#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:289: lines 289-302
						while (($count-- > 0) && (($width === 0) || ($height === 0))) {
							#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:290: lines 290-292
							$tag = $input->readUInt16();
							$type = $input->readUInt16();
							#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:292: characters 18-35
							$input->readInt32();
							#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:293: lines 293-296
							$value = null;
							if ($type === 3) {
								#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:294: characters 17-44
								$t = $input->readUInt16();
								#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:294: characters 45-63
								$input->readUInt16();
								#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:293: lines 293-296
								$value = $t;
							} else {
								$value = $input->readInt32();
							}
							#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:297: lines 297-301
							if ($tag === 256) {
								#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:298: characters 19-32
								$width = $value;
							} else if ($tag === 257) {
								#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:299: characters 19-33
								$height = $value;
							} else {
							}
						}
					} else {
						#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:345: characters 7-31
						$format = "gif";
						#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:346: characters 7-24
						$input->readInt32();
						#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:347: characters 7-33
						$width = $input->readUInt16();
						#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:348: characters 7-34
						$height = $input->readUInt16();
					}
				} else if ($_g === 18770) {
					#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:264: characters 7-38
					$input->seek(6, FileSeek::SeekCur());
					#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:265: lines 265-266
					if ($input->readString(4) !== "WEBP") {
						#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:266: characters 8-46
						return Outcome::Failure(new TypedError(null, $unsupported, new HxAnon([
							"fileName" => "image/Image.hx",
							"lineNumber" => 266,
							"className" => "image.Image",
							"methodName" => "getInfo",
						])));
					}
					#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:267: characters 7-32
					$format = "webp";
					#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:268: characters 14-33
					$__hx__switch = ($input->readString(4));
					if ($__hx__switch === "VP8 ") {
						#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:270: characters 9-41
						$input->seek(10, FileSeek::SeekCur());
						#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:271: characters 9-35
						$width = $input->readUInt16();
						#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:272: characters 9-36
						$height = $input->readUInt16();
					} else if ($__hx__switch === "VP8L") {
						#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:274: characters 9-40
						$input->seek(5, FileSeek::SeekCur());
						#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:275: characters 9-104
						$b0 = $input->readByte();
						$b1 = $input->readByte();
						$b2 = $input->readByte();
						$b3 = $input->readByte();
						#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:276: characters 9-46
						$width = 1 + ((($b1 & 63) << 8) | $b0);
						#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:277: characters 9-75
						$height = 1 + ((($b3 & 15) << 10) | ($b2 << 2) | (($b1 & 192) >> 6));
					} else {
						#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:279: characters 9-47
						return Outcome::Failure(new TypedError(null, $unsupported, new HxAnon([
							"fileName" => "image/Image.hx",
							"lineNumber" => 279,
							"className" => "image.Image",
							"methodName" => "getInfo",
						])));
					}
				} else if ($_g === 19778) {
					#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:281: lines 281-307
					if (($_g === 18761) || ($_g === 19789)) {
						#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:282: characters 7-41
						$input->set_bigEndian($_g === 19789);
						#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:283: lines 283-284
						if ($input->readUInt16() !== 42) {
							#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:284: characters 8-46
							return Outcome::Failure(new TypedError(null, $unsupported, new HxAnon([
								"fileName" => "image/Image.hx",
								"lineNumber" => 284,
								"className" => "image.Image",
								"methodName" => "getInfo",
							])));
						}
						#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:285: characters 7-32
						$format = "tiff";
						#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:286: characters 7-38
						$offset1 = $input->readInt32();
						#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:287: characters 7-45
						$input->seek($offset1, FileSeek::SeekBegin());
						#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:288: characters 7-38
						$count1 = $input->readUInt16();
						#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:289: lines 289-302
						while (($count1-- > 0) && (($width === 0) || ($height === 0))) {
							#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:290: lines 290-292
							$tag1 = $input->readUInt16();
							$type1 = $input->readUInt16();
							#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:292: characters 18-35
							$input->readInt32();
							#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:293: lines 293-296
							$value1 = null;
							if ($type1 === 3) {
								#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:294: characters 17-44
								$t1 = $input->readUInt16();
								#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:294: characters 45-63
								$input->readUInt16();
								#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:293: lines 293-296
								$value1 = $t1;
							} else {
								$value1 = $input->readInt32();
							}
							#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:297: lines 297-301
							if ($tag1 === 256) {
								#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:298: characters 19-32
								$width = $value1;
							} else if ($tag1 === 257) {
								#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:299: characters 19-33
								$height = $value1;
							} else {
							}
						}
					} else {
						#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:304: characters 7-31
						$format = "wbmp";
						#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:305: characters 7-39
						$input->seek(16, FileSeek::SeekCur());
						#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:306: characters 7-32
						$width = $input->readInt32();
						#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:307: characters 7-33
						$height = $input->readInt32();
					}
				} else if ($_g === 20617) {
					#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:281: lines 281-327
					if (($_g === 18761) || ($_g === 19789)) {
						#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:282: characters 7-41
						$input->set_bigEndian($_g === 19789);
						#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:283: lines 283-284
						if ($input->readUInt16() !== 42) {
							#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:284: characters 8-46
							return Outcome::Failure(new TypedError(null, $unsupported, new HxAnon([
								"fileName" => "image/Image.hx",
								"lineNumber" => 284,
								"className" => "image.Image",
								"methodName" => "getInfo",
							])));
						}
						#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:285: characters 7-32
						$format = "tiff";
						#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:286: characters 7-38
						$offset2 = $input->readInt32();
						#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:287: characters 7-45
						$input->seek($offset2, FileSeek::SeekBegin());
						#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:288: characters 7-38
						$count2 = $input->readUInt16();
						#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:289: lines 289-302
						while (($count2-- > 0) && (($width === 0) || ($height === 0))) {
							#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:290: lines 290-292
							$tag2 = $input->readUInt16();
							$type2 = $input->readUInt16();
							#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:292: characters 18-35
							$input->readInt32();
							#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:293: lines 293-296
							$value2 = null;
							if ($type2 === 3) {
								#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:294: characters 17-44
								$t2 = $input->readUInt16();
								#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:294: characters 45-63
								$input->readUInt16();
								#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:293: lines 293-296
								$value2 = $t2;
							} else {
								$value2 = $input->readInt32();
							}
							#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:297: lines 297-301
							if ($tag2 === 256) {
								#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:298: characters 19-32
								$width = $value2;
							} else if ($tag2 === 257) {
								#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:299: characters 19-33
								$height = $value2;
							} else {
							}
						}
					} else {
						#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:309: characters 7-31
						$format = "png";
						#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:310: characters 7-34
						$tmp = Bytes::alloc(256);
						#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:311: characters 7-29
						$input->set_bigEndian(true);
						#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:312: characters 7-33
						$input->readBytes($tmp, 0, 6);
						#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:313: characters 7-19
						$i = 200;
						#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:314: lines 314-327
						while ($i-- > 0) {
							#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:315: characters 8-40
							$dataLen = $input->readInt32();
							#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:316: lines 316-320
							if ($input->readInt32() === 1229472850) {
								#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:317: characters 9-34
								$width = $input->readInt32();
								#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:318: characters 9-35
								$height = $input->readInt32();
								#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:319: characters 9-14
								break;
							}
							#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:321: lines 321-325
							while ($dataLen > 0) {
								#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:322: characters 9-61
								$k = ($dataLen > $tmp->length ? $tmp->length : $dataLen);
								#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:323: characters 9-35
								$input->readBytes($tmp, 0, $k);
								#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:324: characters 9-21
								$dataLen -= $k;
							}
							#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:326: characters 18-35
							$input->readInt32();
						}
					}
				} else if ($_g === 55551) {
					#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:281: lines 281-343
					if (($_g === 18761) || ($_g === 19789)) {
						#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:282: characters 7-41
						$input->set_bigEndian($_g === 19789);
						#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:283: lines 283-284
						if ($input->readUInt16() !== 42) {
							#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:284: characters 8-46
							return Outcome::Failure(new TypedError(null, $unsupported, new HxAnon([
								"fileName" => "image/Image.hx",
								"lineNumber" => 284,
								"className" => "image.Image",
								"methodName" => "getInfo",
							])));
						}
						#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:285: characters 7-32
						$format = "tiff";
						#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:286: characters 7-38
						$offset3 = $input->readInt32();
						#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:287: characters 7-45
						$input->seek($offset3, FileSeek::SeekBegin());
						#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:288: characters 7-38
						$count3 = $input->readUInt16();
						#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:289: lines 289-302
						while (($count3-- > 0) && (($width === 0) || ($height === 0))) {
							#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:290: lines 290-292
							$tag3 = $input->readUInt16();
							$type3 = $input->readUInt16();
							#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:292: characters 18-35
							$input->readInt32();
							#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:293: lines 293-296
							$value3 = null;
							if ($type3 === 3) {
								#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:294: characters 17-44
								$t3 = $input->readUInt16();
								#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:294: characters 45-63
								$input->readUInt16();
								#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:293: lines 293-296
								$value3 = $t3;
							} else {
								$value3 = $input->readInt32();
							}
							#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:297: lines 297-301
							if ($tag3 === 256) {
								#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:298: characters 19-32
								$width = $value3;
							} else if ($tag3 === 257) {
								#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:299: characters 19-33
								$height = $value3;
							} else {
							}
						}
					} else {
						#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:329: characters 7-31
						$format = "jpeg";
						#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:330: characters 7-29
						$input->set_bigEndian(true);
						#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:331: characters 7-19
						$i1 = 200;
						#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:332: lines 332-343
						while ($i1-- > 0) {
							#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:333: characters 15-33
							$__hx__switch = ($input->readUInt16());
							if ($__hx__switch === 65472 || $__hx__switch === 65474) {
								#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:335: characters 20-38
								$input->readUInt16();
								#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:336: characters 21-37
								$input->readByte();
								#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:337: characters 10-37
								$height = $input->readUInt16();
								#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:338: characters 10-36
								$width = $input->readUInt16();
								#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:339: characters 10-15
								break;
							} else {
								#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:341: characters 10-62
								$input->seek($input->readUInt16() - 2, FileSeek::SeekCur());
							}
						};
					}
				} else {
					#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:281: lines 281-350
					if (($_g === 18761) || ($_g === 19789)) {
						#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:282: characters 7-41
						$input->set_bigEndian($_g === 19789);
						#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:283: lines 283-284
						if ($input->readUInt16() !== 42) {
							#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:284: characters 8-46
							return Outcome::Failure(new TypedError(null, $unsupported, new HxAnon([
								"fileName" => "image/Image.hx",
								"lineNumber" => 284,
								"className" => "image.Image",
								"methodName" => "getInfo",
							])));
						}
						#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:285: characters 7-32
						$format = "tiff";
						#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:286: characters 7-38
						$offset4 = $input->readInt32();
						#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:287: characters 7-45
						$input->seek($offset4, FileSeek::SeekBegin());
						#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:288: characters 7-38
						$count4 = $input->readUInt16();
						#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:289: lines 289-302
						while (($count4-- > 0) && (($width === 0) || ($height === 0))) {
							#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:290: lines 290-292
							$tag4 = $input->readUInt16();
							$type4 = $input->readUInt16();
							#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:292: characters 18-35
							$input->readInt32();
							#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:293: lines 293-296
							$value4 = null;
							if ($type4 === 3) {
								#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:294: characters 17-44
								$t4 = $input->readUInt16();
								#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:294: characters 45-63
								$input->readUInt16();
								#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:293: lines 293-296
								$value4 = $t4;
							} else {
								$value4 = $input->readInt32();
							}
							#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:297: lines 297-301
							if ($tag4 === 256) {
								#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:298: characters 19-32
								$width = $value4;
							} else if ($tag4 === 257) {
								#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:299: characters 19-33
								$height = $value4;
							} else {
							}
						}
					} else {
						#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:350: characters 7-45
						return Outcome::Failure(new TypedError(null, $unsupported, new HxAnon([
							"fileName" => "image/Image.hx",
							"lineNumber" => 350,
							"className" => "image.Image",
							"methodName" => "getInfo",
						])));
					}
				}

				#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:352: characters 5-18
				$input->close();
				#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:353: lines 353-357
				return Outcome::Success(new HxAnon([
					"width" => $width,
					"height" => $height,
					"format" => $format,
				]));
			} else if ($__hx__switch === 1) {
				#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:359: characters 17-18
				$e = $res->params[0];
				#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:360: characters 5-22
				return Outcome::Failure($e);
			}
		});
		#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:259: lines 259-361
		return $ret->gather();
	}

	/**
	 * @param string $input
	 * @param string $output
	 * @param object $options
	 * 
	 * @return FutureObject
	 */
	static public function resize ($input, $output, $options) {
		#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:48: characters 3-48
		if ($options->crop === null) {
			#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:48: characters 29-48
			$options->crop = true;
		}
		#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:49: characters 3-60
		if ($options->focus === null) {
			#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:49: characters 30-60
			$options->focus = new HxAnon([
				"x" => .5,
				"y" => .5,
			]);
		}
		#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:51: lines 51-60
		$info = null;
		$ratio = .0;
		$newRatio = .0;
		$cropW = 0;
		$cropH = 0;
		$width = 0;
		$height = 0;
		$sizeRatio = .0;
		$path = new Path($input);
		$tmp = "tn_" . ($path->file??'null') . "." . ($path->ext??'null');
		$xPos = 0;
		$yPos = 0;
		#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:63: lines 63-211
		$ret = Image::getInfo($input)->flatMap(function ($res)  use (&$cropW, &$yPos, &$tmp, &$e, &$width, &$input, &$height, &$cropH, &$output, &$xPos, &$newRatio, &$sizeRatio, &$info, &$ratio, &$options) {
			#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:64: lines 64-211
			$__hx__switch = ($res->index);
			if ($__hx__switch === 0) {
				#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:65: characters 17-18
				$i = $res->params[0];
				#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:66: characters 5-13
				$info = $i;
				#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:67: characters 5-37
				$ratio = $info->width / $info->height;
				#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:68: characters 5-46
				$newRatio = $options->width / $options->height;
				#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:71: lines 71-85
				if ($ratio > $newRatio) {
					#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:73: characters 6-29
					$height = $options->height;
					#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:74: characters 14-48
					$width = (int)(floor($options->height * $ratio + 0.5));
					#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:75: characters 6-25
					$cropH = $info->height;
					#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:76: characters 14-60
					$cropW = (int)(floor($info->width / $width * $options->width + 0.5));
					#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:77: characters 6-46
					$sizeRatio = $options->height / $info->height;
				} else {
					#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:80: characters 15-48
					$height = (int)(floor($options->width / $ratio + 0.5));
					#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:81: characters 6-27
					$width = $options->width;
					#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:82: characters 6-24
					$cropW = $info->width;
					#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:83: characters 14-63
					$cropH = (int)(floor($info->height / $height * $options->height + 0.5));
					#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:84: characters 6-44
					$sizeRatio = $options->width / $info->width;
				}
				#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:87: characters 12-68
				$xPos = (int)(floor($options->focus->x * $info->width - $cropW / 2 + 0.5));
				#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:88: characters 12-69
				$yPos = (int)(floor($options->focus->y * $info->height - $cropH / 2 + 0.5));
				#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:90: characters 5-61
				if (($xPos + $cropW) > $info->width) {
					#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:90: characters 36-61
					$xPos = $info->width - $cropW;
				}
				#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:91: characters 5-63
				if (($yPos + $cropH) > $info->height) {
					#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:91: characters 37-63
					$yPos = $info->height - $cropH;
				}
				#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:92: characters 5-27
				if ($xPos < 0) {
					#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:92: characters 19-27
					$xPos = 0;
				}
				#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:93: characters 5-27
				if ($yPos < 0) {
					#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:93: characters 19-27
					$yPos = 0;
				}
				#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:135: lines 135-172
				if ($options->engine->index === 3) {
					#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:136: lines 136-172
					try {
						#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:137: characters 8-55
						$createFrom = "imagecreatefrom" . ($info->format??'null');
						#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:139: characters 7-61
						$src = $createFrom($input);
						#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:141: characters 7-73
						$dst = imagecreatetruecolor($options->width, $options->height);
						#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:143: characters 7-41
						$outputPath = new Path($output);
						#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:144: lines 144-151
						if ($outputPath->ext === "png") {
							#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:145: lines 145-150
							if (function_exists('imagecolorallocatealpha')) {
								imagealphablending($dst, false);
								imagesavealpha($dst, true);
								$transparent = imagecolorallocatealpha($dst, 255, 255, 255, 127);
								imagefilledrectangle($dst, 0, 0, $options->width, $options->height, $transparent);
							};
						}
						#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:152: characters 7-102
						imagecopyresampled($dst, $src, 0, 0, $xPos, $yPos, $options->width, $options->height, $cropW, $cropH);
						#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:153: characters 7-28
						imagedestroy($src);
						#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:154: characters 14-42
						$__hx__switch = (mb_strtolower($outputPath->ext));
						if ($__hx__switch === "bmp") {
							#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:162: characters 10-36
							imagewbmp($dst, $output);
						} else if ($__hx__switch === "gif") {
							#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:156: characters 10-35
							imagegif($dst, $output);
						} else if ($__hx__switch === "jpeg" || $__hx__switch === "jpg") {
							#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:158: characters 10-40
							imagejpeg($dst, $output, 96);
						} else if ($__hx__switch === "png") {
							#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:160: characters 10-38
							imagepng($dst, $output, 9);
						} else {
							#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:165: characters 9-51
							$outFunc($dst, $output);
						}
						#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:168: characters 7-27
						imagedestroy($dst);
						#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:169: characters 14-41
						return new SyncFuture(new LazyConst(Outcome::Success(Noise::Noise())));
					} catch (\Throwable $__hx__caught_e) {
						$__hx__real_e = ($__hx__caught_e instanceof HxException ? $__hx__caught_e->e : $__hx__caught_e);
						$e = $__hx__real_e;
						#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:171: characters 14-37
						return new SyncFuture(new LazyConst(Outcome::Failure($e)));
					}
				}
				#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:175: characters 5-40
				$xPos = (int)(floor($xPos * $sizeRatio + 0.5));
				#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:176: characters 5-40
				$yPos = (int)(floor($yPos * $sizeRatio + 0.5));
				#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:178: lines 178-183
				$cmd = null;
				#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:178: characters 22-36
				$__hx__switch = ($options->engine->index);
				if ($__hx__switch === 0) {
					#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:178: lines 178-183
					$cmd = "vipsthumbnail";
				} else if ($__hx__switch === 1) {
					$cmd = "convert";
				} else if ($__hx__switch === 2) {
					$cmd = "gm";
				} else {
					$cmd = null;
				}
				#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:184: lines 184-200
				$args = null;
				#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:184: characters 23-37
				$__hx__switch = ($options->engine->index);
				if ($__hx__switch === 0) {
					#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:184: lines 184-200
					$args = \Array_hx::wrap([
						$input,
						"-s",
						"" . ($width??'null') . "x" . ($height??'null'),
						"-c",
						"-o",
						$tmp,
					]);
				} else if ($__hx__switch === 1) {
					$args = \Array_hx::wrap([
						$input,
						"-resize",
						"" . ($width??'null') . "x" . ($height??'null'),
						"-crop",
						"" . ($options->width??'null') . "x" . ($options->height??'null') . "+" . ($xPos??'null') . "+" . ($yPos??'null'),
						"-strip",
						"+repage",
						$output,
					]);
				} else if ($__hx__switch === 2) {
					$args = \Array_hx::wrap([
						"convert",
						$input,
						"-resize",
						"" . ($width??'null') . "x" . ($height??'null'),
						"-crop",
						"" . ($options->width??'null') . "x" . ($options->height??'null') . "+" . ($xPos??'null') . "+" . ($yPos??'null'),
						"-strip",
						"+repage",
						$output,
					]);
				} else {
					$args = null;
				}
				#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:201: characters 5-42
				$process = new Process($cmd, $args);
				#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:202: lines 202-208
				return Future_Impl_::_map($process->exitCode(), function ($code) {
					#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:203: lines 203-208
					if ($code === 0) {
						#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:205: characters 7-21
						return Outcome::Success(Noise::Noise());
					} else {
						#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:207: characters 7-62
						return Outcome::Failure(new TypedError(null, "Resize process exited with: " . ($code??'null'), new HxAnon([
							"fileName" => "image/Image.hx",
							"lineNumber" => 207,
							"className" => "image.Image",
							"methodName" => "resize",
						])));
					}
				});
			} else if ($__hx__switch === 1) {
				#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:209: characters 17-18
				$e1 = $res->params[0];
				#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:210: characters 5-28
				return new SyncFuture(new LazyConst(Outcome::Failure($e1)));
			}
		});
		#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:63: lines 63-236
		$ret1 = $ret->gather()->flatMap(function ($res1)  use (&$yPos, &$tmp, &$output, &$xPos, &$options, &$path) {
			#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:212: lines 212-236
			$__hx__switch = ($res1->index);
			if ($__hx__switch === 0) {
				#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:214: characters 12-26
				if ($options->engine->index !== 0) {
					#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:217: characters 14-41
					return new SyncFuture(new LazyConst(Outcome::Success(Noise::Noise())));
				}
				#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:222: characters 7-33
				$process1 = Path::join(\Array_hx::wrap([
					$path->dir,
					$tmp,
				]));
				#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:220: lines 220-225
				$process2 = new Process("vips", \Array_hx::wrap([
					"crop",
					$process1,
					$output,
					"" . ($xPos??'null'),
					"" . ($yPos??'null'),
					"" . ($options->width??'null'),
					"" . ($options->height??'null'),
				]));
				#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:227: lines 227-233
				return Future_Impl_::_map($process2->exitCode(), function ($code1) {
					#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:228: lines 228-233
					if ($code1 === 0) {
						#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:230: characters 7-21
						return Outcome::Success(Noise::Noise());
					} else {
						#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:232: characters 7-60
						return Outcome::Failure(new TypedError(null, "Crop process exited with: " . ($code1??'null'), new HxAnon([
							"fileName" => "image/Image.hx",
							"lineNumber" => 232,
							"className" => "image.Image",
							"methodName" => "resize",
						])));
					}
				});
			} else if ($__hx__switch === 1) {
				#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:234: characters 17-18
				$e2 = $res1->params[0];
				#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:235: characters 5-28
				return new SyncFuture(new LazyConst(Outcome::Failure($e2)));
			}
		});
		#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:62: lines 62-247
		return Future_Impl_::_flatMap($ret1->gather(), function ($res2)  use (&$tmp, &$options, &$path) {
			#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:237: lines 237-247
			$__hx__switch = ($res2->index);
			if ($__hx__switch === 0) {
				#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:239: characters 12-26
				if ($options->engine->index !== 0) {
					#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:242: characters 14-41
					return new SyncFuture(new LazyConst(Outcome::Success(Noise::Noise())));
				}
				#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:244: characters 5-54
				return FileSystem::deleteFile(Path::join(\Array_hx::wrap([
					$path->dir,
					$tmp,
				])));
			} else if ($__hx__switch === 1) {
				#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:245: characters 17-18
				$e3 = $res2->params[0];
				#/Users/ut/haxe/haxe_libraries/image/0.1.1/github/c562ccff20a8be16d1acd02536bcfa94a4d10ba8/src/image/Image.hx:246: characters 5-28
				return new SyncFuture(new LazyConst(Outcome::Failure($e3)));
			}
		});
	}
}

Boot::registerClass(Image::class, 'image.Image');
