<?php
/**
 * Generated by Haxe 4.0.0-rc.2+77068e1
 * Haxe source file: /Users/ut/haxe/haxe_libraries/tink_http/0.8.2/github/c95e2dc46654779b496e5f99d01241b1d572e33c/src/tink/http/Response.hx
 */

namespace tink\http\_Response;

use \php\Boot;
use \tink\streams\StreamObject;
use \tink\http\ResponseHeaderBase;
use \tink\http\Message;

class OutgoingResponseData extends Message {
	/**
	 * @param ResponseHeaderBase $header
	 * @param StreamObject $body
	 * 
	 * @return void
	 */
	public function __construct ($header, $body) {
		#/Users/ut/haxe/haxe_libraries/tink_http/0.8.2/github/c95e2dc46654779b496e5f99d01241b1d572e33c/src/tink/http/Response.hx:61: characters 9-83
		parent::__construct($header, $body);
	}
}

Boot::registerClass(OutgoingResponseData::class, 'tink.http._Response.OutgoingResponseData');
