<?php
/**
 * Generated by Haxe 4.0.0-rc.2+77068e1
 * Haxe source file: /Users/ut/haxe/haxe_libraries/tink_web/0.1.4/github/c4323c7b0c2f0b44e696eea51c9bfdff41716880/src/tink/web/Response.hx
 */

namespace tink\web\_Response;

use \php\Boot;
use \tink\http\ResponseHeaderBase;
use \tink\http\Message;

final class Response_Impl_ {
	/**
	 * @param ResponseHeaderBase $header
	 * @param mixed $body
	 * 
	 * @return Message
	 */
	static public function _new ($header, $body) {
		#/Users/ut/haxe/haxe_libraries/tink_web/0.1.4/github/c4323c7b0c2f0b44e696eea51c9bfdff41716880/src/tink/web/Response.hx:10: character 2
		$this1 = new Message($header, $body);
		return $this1;
	}

	/**
	 * @param Message $this
	 * 
	 * @return mixed
	 */
	static public function getData ($this1) {
		#/Users/ut/haxe/haxe_libraries/tink_web/0.1.4/github/c4323c7b0c2f0b44e696eea51c9bfdff41716880/src/tink/web/Response.hx:15: characters 3-19
		return $this1->body;
	}
}

Boot::registerClass(Response_Impl_::class, 'tink.web._Response.Response_Impl_');
