<?php
/**
 * Generated by Haxe 4.0.0-rc.2+77068e1
 * Haxe source file: src/app/Server.hx
 */

namespace app;

use \apis\FileApi;
use \php\_Boot\HxAnon;
use \command\MyCommand;
use \views\Layout;
use \php\Boot;
use \wire\Actor;
use \views\__impl\Header;
use \command\MyCommand2;
use \wire\_ActionCommand\ActionCommand_Impl_;
use \views\__impl\Footer;
use \views\__impl\Home;
use \views\__impl\Menu;
use \tink\core\_Future\FutureObject;

class Root implements IRemoteRoot {
	/**
	 * @var SQLiteRoute
	 */
	public $whatever;

	/**
	 * @return void
	 */
	public function __construct () {
		#src/app/Server.hx:61: characters 27-44
		$this->whatever = new SQLiteRoute();
		#src/app/Server.hx:49: characters 3-43
		Actor::set_defaultLayout(new Layout());
		#src/app/Server.hx:50: characters 3-54
		Actor::$defaultLayout->footer = Footer::render();
		#src/app/Server.hx:51: lines 51-55
		$nav = \Array_hx::wrap([new HxAnon([
			"url" => "/rss",
			"title" => "abonne toi en afrique ",
			"description" => "le flux nrss du podcast",
		])]);
		#src/app/Server.hx:56: characters 3-52
		Actor::$defaultLayout->menu = Menu::render($nav);
		#src/app/Server.hx:57: characters 3-53
		Actor::$defaultLayout->header = Header::render();
	}

	/**
	 * @return string
	 */
	public function hello () {
		#src/app/Server.hx:69: characters 3-102
		return Actor::addAction(Actor::addAction(Actor::withLayout(Home::render()), ActionCommand_Impl_::toString(Boot::getClass(MyCommand::class))), ActionCommand_Impl_::toString(Boot::getClass(MyCommand2::class)), "bingo")->render();
	}

	/**
	 * @return string
	 */
	public function rss () {
		#src/app/Server.hx:75: characters 3-102
		return Actor::addAction(Actor::addAction(Actor::withLayout(Home::render()), ActionCommand_Impl_::toString(Boot::getClass(MyCommand::class))), ActionCommand_Impl_::toString(Boot::getClass(MyCommand2::class)), "bongo")->render();
	}

	/**
	 * @param object $body
	 * 
	 * @return FutureObject
	 */
	public function uploadFile ($body) {
		#src/app/Server.hx:81: characters 4-37
		return FileApi::saveImg($body->file);
	}
}

Boot::registerClass(Root::class, 'app.Root');
