<?php
/**
 * Generated by Haxe 4.0.0-rc.1+1fdd3d5
 * Haxe source file: src/app/TinkLiteRoute.hx
 */

namespace app;

use \php\Boot;
use \apis\tinklite\RecLiteApi;
use \tink\core\_Future\FutureObject;

class TinkLiteRoute {
	/**
	 * @var RecLiteApi
	 */
	public $recApi;

	/**
	 * @return void
	 */
	public function __construct () {
	}

	/**
	 * @return FutureObject
	 */
	public function all () {
		#src/app/TinkLiteRoute.hx:26: characters 3-29
		$this->recApi = RecLiteApi::init();
		#src/app/TinkLiteRoute.hx:27: characters 3-25
		return $this->recApi->getAll();
	}

	/**
	 * @return FutureObject
	 */
	public function create () {
		#src/app/TinkLiteRoute.hx:40: characters 4-31
		return RecLiteApi::create();
	}

	/**
	 * @param int $id
	 * 
	 * @return FutureObject
	 */
	public function get ($id = null) {
		#src/app/TinkLiteRoute.hx:18: characters 3-29
		$this->recApi = RecLiteApi::init();
		#src/app/TinkLiteRoute.hx:21: characters 3-24
		return $this->recApi->get($id);
	}

	/**
	 * @return FutureObject
	 */
	public function rec () {
		#src/app/TinkLiteRoute.hx:32: characters 3-29
		$this->recApi = RecLiteApi::init();
		#src/app/TinkLiteRoute.hx:33: characters 3-84
		return $this->recApi->saveRec("philo.mp3", "naturelle", "terme archaique", 0, "ceci.jpg");
	}

	/**
	 * @return string
	 */
	public function tst () {
		#src/app/TinkLiteRoute.hx:12: characters 5-29
		$this->recApi = RecLiteApi::init();
		#src/app/TinkLiteRoute.hx:14: characters 5-24
		return $this->recApi->tst();
	}
}

Boot::registerClass(TinkLiteRoute::class, 'app.TinkLiteRoute');
