<?php
/**
 * Generated by Haxe 4.0.0-rc.2+77068e1
 * Haxe source file: /Users/ut/haxe/haxe_libraries/tink_core/1.20.0/haxelib/src/tink/core/Promise.hx
 */

namespace tink\core\_Promise;

use \tink\core\_Future\SyncFuture;
use \php\Boot;
use \tink\core\Outcome;
use \tink\core\_Lazy\LazyConst;

final class Next_Impl_ {
	/**
	 * @param \Closure $a
	 * @param \Closure $b
	 * 
	 * @return \Closure
	 */
	static public function _chain ($a, $b) {
		#/Users/ut/haxe/haxe_libraries/tink_core/1.20.0/haxelib/src/tink/core/Promise.hx:253: characters 5-44
		return function ($v)  use (&$b, &$a) {
			#/Users/ut/haxe/haxe_libraries/tink_core/1.20.0/haxelib/src/tink/core/Promise.hx:253: characters 25-44
			return Promise_Impl_::next($a($v), $b);
		};
	}

	/**
	 * @param \Closure $f
	 * 
	 * @return \Closure
	 */
	static public function ofSafe ($f) {
		#/Users/ut/haxe/haxe_libraries/tink_core/1.20.0/haxelib/src/tink/core/Promise.hx:244: characters 5-36
		return function ($x)  use (&$f) {
			#/Users/ut/haxe/haxe_libraries/tink_core/1.20.0/haxelib/src/tink/core/Promise.hx:244: characters 25-36
			return new SyncFuture(new LazyConst($f($x)));
		};
	}

	/**
	 * @param \Closure $f
	 * 
	 * @return \Closure
	 */
	static public function ofSafeSync ($f) {
		#/Users/ut/haxe/haxe_libraries/tink_core/1.20.0/haxelib/src/tink/core/Promise.hx:250: characters 5-36
		return function ($x)  use (&$f) {
			#/Users/ut/haxe/haxe_libraries/tink_core/1.20.0/haxelib/src/tink/core/Promise.hx:250: characters 25-36
			return new SyncFuture(new LazyConst(Outcome::Success($f($x))));
		};
	}

	/**
	 * @param \Closure $f
	 * 
	 * @return \Closure
	 */
	static public function ofSync ($f) {
		#/Users/ut/haxe/haxe_libraries/tink_core/1.20.0/haxelib/src/tink/core/Promise.hx:247: characters 5-36
		return function ($x)  use (&$f) {
			#/Users/ut/haxe/haxe_libraries/tink_core/1.20.0/haxelib/src/tink/core/Promise.hx:247: characters 25-36
			$ret = $f($x)->map(Boot::getStaticClosure(Outcome::class, 'Success'));
			return $ret->gather();
		};
	}
}

Boot::registerClass(Next_Impl_::class, 'tink.core._Promise.Next_Impl_');
