<?php
/**
 * Generated by Haxe 4.0.0-rc.2+77068e1
 * Haxe source file: /Users/ut/haxe/haxe_libraries/tink_web/0.1.4/github/c4323c7b0c2f0b44e696eea51c9bfdff41716880/src/tink/web/routing/Router.hx
 */

namespace tink\web\routing;

use \php\Boot;

class Router {
}

Boot::registerClass(Router::class, 'tink.web.routing.Router');
