<?php
/**
 * Generated by Haxe 4.0.0-rc.2+77068e1
 * Haxe source file: /Users/ut/haxe/haxe_libraries/tink_web/0.1.4/github/c4323c7b0c2f0b44e696eea51c9bfdff41716880/src/tink/web/macros/Routing.hx
 */

namespace tink\web\routing;

use \php\_Boot\HxAnon;
use \tink\core\_Future\SyncFuture;
use \tink\querystring\_Pairs\Pairs_Impl_;
use \php\Boot;
use \tink\core\TypedError;
use \tink\core\Outcome;
use \tink\querystring\Parser0 as QuerystringParser0;
use \tink\json\Parser0;
use \tink\core\_Lazy\LazyConst;
use \app\Root;
use \tink\json\Writer0;
use \tink\core\_Promise\Next_Impl_;
use \tink\web\routing\_Response\Response_Impl_;
use \tink\core\_Promise\Promise_Impl_;
use \tink\core\_Future\FutureObject;

class Router0 {
	/**
	 * @var Root
	 */
	public $target;

	/**
	 * @param Root $target
	 * 
	 * @return void
	 */
	public function __construct ($target) {
		#/Users/ut/haxe/haxe_libraries/tink_web/0.1.4/github/c4323c7b0c2f0b44e696eea51c9bfdff41716880/src/tink/web/macros/Routing.hx:218: characters 11-31
		$this->target = $target;
	}

	/**
	 * @param Context $ctx
	 * 
	 * @return FutureObject
	 */
	public function hello ($ctx) {
		#src/app/Server.hx:67: lines 67-70
		return Promise_Impl_::next(new SyncFuture(new LazyConst(Outcome::Success($this->target->hello()))), Next_Impl_::ofSafeSync(function ($v) {
			return Response_Impl_::ofHtml($v);
		}));
	}

	/**
	 * @param Context $ctx
	 * 
	 * @return FutureObject
	 */
	public function route ($ctx) {
		#/Users/ut/haxe/haxe_libraries/tink_web/0.1.4/github/c4323c7b0c2f0b44e696eea51c9bfdff41716880/src/tink/web/macros/Routing.hx:222: characters 11-34
		$l = $ctx->parts->length - $ctx->depth;
		#/Users/ut/haxe/haxe_libraries/tink_web/0.1.4/github/c4323c7b0c2f0b44e696eea51c9bfdff41716880/src/tink/web/macros/Routing.hx:143: characters 22-31
		$_g = $l > 1;
		$_g1 = $l > 0;
		#/Users/ut/haxe/haxe_libraries/tink_web/0.1.4/github/c4323c7b0c2f0b44e696eea51c9bfdff41716880/src/tink/web/macros/Routing.hx:140: characters 22-41
		$_g2 = $ctx->part(0);
		#/Users/ut/haxe/haxe_libraries/tink_web/0.1.4/github/c4323c7b0c2f0b44e696eea51c9bfdff41716880/src/tink/web/macros/Routing.hx:137: characters 22-39
		$_g3 = $ctx->request->header->method;
		#/Users/ut/haxe/haxe_libraries/tink_web/0.1.4/github/c4323c7b0c2f0b44e696eea51c9bfdff41716880/src/tink/web/macros/Routing.hx:140: characters 22-41
		if ($_g2 === "rss") {
			#/Users/ut/haxe/haxe_libraries/tink_web/0.1.4/github/c4323c7b0c2f0b44e696eea51c9bfdff41716880/src/tink/web/macros/Routing.hx:137: characters 22-39
			if ($_g3 === "GET") {
				#/Users/ut/haxe/haxe_libraries/tink_web/0.1.4/github/c4323c7b0c2f0b44e696eea51c9bfdff41716880/src/tink/web/macros/Routing.hx:143: characters 22-31
				if ($_g1 === false) {
					#src/app/Server.hx:66: characters 8-11
					return Promise_Impl_::ofSpecific($this->hello($ctx));
				} else if ($_g1 === true) {
					#/Users/ut/haxe/haxe_libraries/tink_web/0.1.4/github/c4323c7b0c2f0b44e696eea51c9bfdff41716880/src/tink/web/macros/Routing.hx:143: characters 22-31
					if ($_g === false) {
						#src/app/Server.hx:71: characters 8-14
						return Promise_Impl_::ofSpecific($this->rss($ctx));
					} else {
						#src/app/Server.hx:34: characters 20-32
						$this1 = $ctx->request->header->url;
						return new SyncFuture(new LazyConst(Outcome::Failure(new TypedError(404, "Not Found: [" . ($ctx->request->header->method??'null') . "] " . ((($this1->query === null ? $this1->path : ($this1->path??'null') . "?" . ($this1->query??'null')))??'null'), new HxAnon([
							"fileName" => "src/app/Server.hx",
							"lineNumber" => 34,
							"className" => "tink.web.routing.Router0",
							"methodName" => "route",
						])))));
					}
				}
			} else {
				$this11 = $ctx->request->header->url;
				return new SyncFuture(new LazyConst(Outcome::Failure(new TypedError(404, "Not Found: [" . ($ctx->request->header->method??'null') . "] " . ((($this11->query === null ? $this11->path : ($this11->path??'null') . "?" . ($this11->query??'null')))??'null'), new HxAnon([
					"fileName" => "src/app/Server.hx",
					"lineNumber" => 34,
					"className" => "tink.web.routing.Router0",
					"methodName" => "route",
				])))));
			}
		} else if ($_g2 === "sqlit") {
			#/Users/ut/haxe/haxe_libraries/tink_web/0.1.4/github/c4323c7b0c2f0b44e696eea51c9bfdff41716880/src/tink/web/macros/Routing.hx:143: characters 22-31
			if ($_g1 === false) {
				#/Users/ut/haxe/haxe_libraries/tink_web/0.1.4/github/c4323c7b0c2f0b44e696eea51c9bfdff41716880/src/tink/web/macros/Routing.hx:137: characters 22-39
				if ($_g3 === "GET") {
					#src/app/Server.hx:66: characters 8-11
					return Promise_Impl_::ofSpecific($this->hello($ctx));
				} else {
					#src/app/Server.hx:34: characters 20-32
					$this12 = $ctx->request->header->url;
					return new SyncFuture(new LazyConst(Outcome::Failure(new TypedError(404, "Not Found: [" . ($ctx->request->header->method??'null') . "] " . ((($this12->query === null ? $this12->path : ($this12->path??'null') . "?" . ($this12->query??'null')))??'null'), new HxAnon([
						"fileName" => "src/app/Server.hx",
						"lineNumber" => 34,
						"className" => "tink.web.routing.Router0",
						"methodName" => "route",
					])))));
				}
			} else if ($_g1 === true) {
				#src/app/Server.hx:59: characters 8-17
				return $this->whatever($ctx, 1);
			}
		} else if ($_g2 === "uploadFile") {
			#/Users/ut/haxe/haxe_libraries/tink_web/0.1.4/github/c4323c7b0c2f0b44e696eea51c9bfdff41716880/src/tink/web/macros/Routing.hx:137: characters 22-39
			if ($_g3 === "GET") {
				#/Users/ut/haxe/haxe_libraries/tink_web/0.1.4/github/c4323c7b0c2f0b44e696eea51c9bfdff41716880/src/tink/web/macros/Routing.hx:143: characters 22-31
				if ($_g1 === false) {
					#src/app/Server.hx:66: characters 8-11
					return Promise_Impl_::ofSpecific($this->hello($ctx));
				} else {
					#src/app/Server.hx:34: characters 20-32
					$this13 = $ctx->request->header->url;
					return new SyncFuture(new LazyConst(Outcome::Failure(new TypedError(404, "Not Found: [" . ($ctx->request->header->method??'null') . "] " . ((($this13->query === null ? $this13->path : ($this13->path??'null') . "?" . ($this13->query??'null')))??'null'), new HxAnon([
						"fileName" => "src/app/Server.hx",
						"lineNumber" => 34,
						"className" => "tink.web.routing.Router0",
						"methodName" => "route",
					])))));
				}
			} else if ($_g3 === "POST") {
				#/Users/ut/haxe/haxe_libraries/tink_web/0.1.4/github/c4323c7b0c2f0b44e696eea51c9bfdff41716880/src/tink/web/macros/Routing.hx:143: characters 22-31
				if (($_g1 === true) && ($_g === false)) {
					#src/app/Server.hx:78: characters 10-23
					return Promise_Impl_::ofSpecific($this->uploadFile($ctx));
				} else {
					#src/app/Server.hx:34: characters 20-32
					$this14 = $ctx->request->header->url;
					return new SyncFuture(new LazyConst(Outcome::Failure(new TypedError(404, "Not Found: [" . ($ctx->request->header->method??'null') . "] " . ((($this14->query === null ? $this14->path : ($this14->path??'null') . "?" . ($this14->query??'null')))??'null'), new HxAnon([
						"fileName" => "src/app/Server.hx",
						"lineNumber" => 34,
						"className" => "tink.web.routing.Router0",
						"methodName" => "route",
					])))));
				}
			} else {
				$this15 = $ctx->request->header->url;
				return new SyncFuture(new LazyConst(Outcome::Failure(new TypedError(404, "Not Found: [" . ($ctx->request->header->method??'null') . "] " . ((($this15->query === null ? $this15->path : ($this15->path??'null') . "?" . ($this15->query??'null')))??'null'), new HxAnon([
					"fileName" => "src/app/Server.hx",
					"lineNumber" => 34,
					"className" => "tink.web.routing.Router0",
					"methodName" => "route",
				])))));
			}
		} else {
			#/Users/ut/haxe/haxe_libraries/tink_web/0.1.4/github/c4323c7b0c2f0b44e696eea51c9bfdff41716880/src/tink/web/macros/Routing.hx:137: characters 22-39
			if (($_g3 === "GET") && ($_g1 === false)) {
				#src/app/Server.hx:66: characters 8-11
				return Promise_Impl_::ofSpecific($this->hello($ctx));
			} else {
				#src/app/Server.hx:34: characters 20-32
				$this16 = $ctx->request->header->url;
				return new SyncFuture(new LazyConst(Outcome::Failure(new TypedError(404, "Not Found: [" . ($ctx->request->header->method??'null') . "] " . ((($this16->query === null ? $this16->path : ($this16->path??'null') . "?" . ($this16->query??'null')))??'null'), new HxAnon([
					"fileName" => "src/app/Server.hx",
					"lineNumber" => 34,
					"className" => "tink.web.routing.Router0",
					"methodName" => "route",
				])))));
			}
		}
	}

	/**
	 * @param Context $ctx
	 * 
	 * @return FutureObject
	 */
	public function rss ($ctx) {
		#src/app/Server.hx:72: lines 72-76
		return Promise_Impl_::next(new SyncFuture(new LazyConst(Outcome::Success($this->target->rss()))), Next_Impl_::ofSafeSync(function ($v) {
			return Response_Impl_::ofHtml($v);
		}));
	}

	/**
	 * @param Context $ctx
	 * 
	 * @return FutureObject
	 */
	public function uploadFile ($ctx) {
		#src/app/Server.hx:79: lines 79-82
		$_gthis = $this;
		$_g1 = null;
		$_g = $ctx->request->header->contentType();
		if ($_g->index === 0) {
			$v = $_g->params[0];
			$_g1 = "" . ($v->type??'null') . "/" . ($v->subtype??'null');
		} else {
			$_g1 = "application/json";
		}
		$tmp = null;
		if ($_g1 === "application/json") {
			$tmp = Promise_Impl_::next($ctx->allRaw(), function ($b) {
				return new SyncFuture(new LazyConst((new Parser0())->tryParse($b->toString())));
			});
		} else if ($_g1 === "application/x-www-form-urlencoded") {
			$tmp = Promise_Impl_::next($ctx->parse(), function ($pairs) {
				return new SyncFuture(new LazyConst((new QuerystringParser0())->tryParse(Pairs_Impl_::ofIterable($pairs))));
			});
		} else {
			#/Users/ut/haxe/haxe_libraries/tink_web/0.1.4/github/c4323c7b0c2f0b44e696eea51c9bfdff41716880/src/tink/web/macros/Routing.hx:660: characters 22-29
			$invalid = $_g1;
			#src/app/Server.hx:79: lines 79-82
			$tmp = new SyncFuture(new LazyConst(Outcome::Failure(new TypedError(406, "Cannot process Content-Type " . ($invalid??'null'), new HxAnon([
				"fileName" => "tink/web/macros/Routing.hx",
				"lineNumber" => 661,
				"className" => "tink.web.routing.Router0",
				"methodName" => "uploadFile",
			])))));
		}
		return Promise_Impl_::next($tmp, function ($body)  use (&$_gthis, &$ctx) {
			return Promise_Impl_::next($_gthis->target->uploadFile($body), function ($__data__)  use (&$ctx) {
				if (($ctx->accepts)("application/json")) {
					return new SyncFuture(new LazyConst(Outcome::Success(Response_Impl_::textual(null, "application/json", (new Writer0())->write($__data__)))));
				}
				return new SyncFuture(new LazyConst(Outcome::Failure(new TypedError(415, "Unsupported Media Type", new HxAnon([
					"fileName" => "src/app/Server.hx",
					"lineNumber" => 79,
					"className" => "tink.web.routing.Router0",
					"methodName" => "uploadFile",
				])))));
			});
		});
	}

	/**
	 * @param Context $ctx
	 * @param int $__depth__
	 * 
	 * @return FutureObject
	 */
	public function whatever ($ctx, $__depth__) {
		#/Users/ut/haxe/haxe_libraries/tink_web/0.1.4/github/c4323c7b0c2f0b44e696eea51c9bfdff41716880/src/tink/web/macros/Routing.hx:368: characters 13-42
		$ctx1 = $ctx->sub($__depth__);
		#src/app/Server.hx:61: characters 5-45
		return Promise_Impl_::next(new SyncFuture(new LazyConst(Outcome::Success($this->target->whatever))), function ($__target__)  use (&$ctx1) {
			return (new Router1($__target__))->route($ctx1);
		});
	}
}

Boot::registerClass(Router0::class, 'tink.web.routing.Router0');
