<?php
/**
 * Generated by Haxe 4.0.0-rc.2+77068e1
 * Haxe source file: /Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Representation.hx
 */

namespace tink\json\_Representation;

use \php\Boot;

final class Representation_Impl_ {
	/**
	 * @param mixed $v
	 * 
	 * @return mixed
	 */
	static public function _new ($v) {
		#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Representation.hx:8: character 3
		return $v;
	}

	/**
	 * @param mixed $this
	 * 
	 * @return mixed
	 */
	static public function get ($this1) {
		#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Representation.hx:6: characters 5-16
		return $this1;
	}

	/**
	 * @param mixed $v
	 * 
	 * @return mixed
	 */
	static public function of ($v) {
		#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Representation.hx:12: characters 5-13
		return $v;
	}
}

Boot::registerClass(Representation_Impl_::class, 'tink.json._Representation.Representation_Impl_');
