<?php
/**
 * Generated by Haxe 4.0.0-rc.2+77068e1
 * Haxe source file: /Users/ut/haxe/haxe_libraries/tink_core/1.20.0/haxelib/src/tink/core/Outcome.hx
 */

namespace tink\core\_Outcome;

use \php\_Boot\HxAnon;
use \php\Boot;
use \haxe\ds\Either;
use \tink\core\Outcome;

final class OutcomeMapper_Impl_ {
	/**
	 * @param \Closure $f
	 * 
	 * @return object
	 */
	static public function _new ($f) {
		#/Users/ut/haxe/haxe_libraries/tink_core/1.20.0/haxelib/src/tink/core/Outcome.hx:150: character 3
		$this1 = new HxAnon(["f" => $f]);
		return $this1;
	}

	/**
	 * @param object $this
	 * @param Outcome $o
	 * 
	 * @return Outcome
	 */
	static public function apply ($this1, $o) {
		#/Users/ut/haxe/haxe_libraries/tink_core/1.20.0/haxelib/src/tink/core/Outcome.hx:152: characters 5-21
		return $this1->f($o);
	}

	/**
	 * @param \Closure $f
	 * 
	 * @return object
	 */
	static public function withEitherError ($f) {
		#/Users/ut/haxe/haxe_libraries/tink_core/1.20.0/haxelib/src/tink/core/Outcome.hx:164: lines 164-173
		return OutcomeMapper_Impl_::_new(function ($o)  use (&$f) {
			#/Users/ut/haxe/haxe_libraries/tink_core/1.20.0/haxelib/src/tink/core/Outcome.hx:165: lines 165-172
			$__hx__switch = ($o->index);
			if ($__hx__switch === 0) {
				#/Users/ut/haxe/haxe_libraries/tink_core/1.20.0/haxelib/src/tink/core/Outcome.hx:166: characters 22-23
				$d = $o->params[0];
				#/Users/ut/haxe/haxe_libraries/tink_core/1.20.0/haxelib/src/tink/core/Outcome.hx:167: characters 18-22
				$_g = $f($d);
				$__hx__switch = ($_g->index);
				if ($__hx__switch === 0) {
					#/Users/ut/haxe/haxe_libraries/tink_core/1.20.0/haxelib/src/tink/core/Outcome.hx:168: characters 26-27
					$d1 = $_g->params[0];
					#/Users/ut/haxe/haxe_libraries/tink_core/1.20.0/haxelib/src/tink/core/Outcome.hx:168: characters 30-40
					return Outcome::Success($d1);
				} else if ($__hx__switch === 1) {
					#/Users/ut/haxe/haxe_libraries/tink_core/1.20.0/haxelib/src/tink/core/Outcome.hx:169: characters 26-27
					$f1 = $_g->params[0];
					#/Users/ut/haxe/haxe_libraries/tink_core/1.20.0/haxelib/src/tink/core/Outcome.hx:169: characters 30-47
					return Outcome::Failure(Either::Right($f1));
				}
			} else if ($__hx__switch === 1) {
				#/Users/ut/haxe/haxe_libraries/tink_core/1.20.0/haxelib/src/tink/core/Outcome.hx:171: characters 22-23
				$f2 = $o->params[0];
				#/Users/ut/haxe/haxe_libraries/tink_core/1.20.0/haxelib/src/tink/core/Outcome.hx:171: characters 26-42
				return Outcome::Failure(Either::Left($f2));
			}
		});
	}

	/**
	 * @param \Closure $f
	 * 
	 * @return object
	 */
	static public function withSameError ($f) {
		#/Users/ut/haxe/haxe_libraries/tink_core/1.20.0/haxelib/src/tink/core/Outcome.hx:155: lines 155-160
		return OutcomeMapper_Impl_::_new(function ($o)  use (&$f) {
			#/Users/ut/haxe/haxe_libraries/tink_core/1.20.0/haxelib/src/tink/core/Outcome.hx:156: lines 156-159
			$__hx__switch = ($o->index);
			if ($__hx__switch === 0) {
				#/Users/ut/haxe/haxe_libraries/tink_core/1.20.0/haxelib/src/tink/core/Outcome.hx:157: characters 22-23
				$d = $o->params[0];
				#/Users/ut/haxe/haxe_libraries/tink_core/1.20.0/haxelib/src/tink/core/Outcome.hx:157: characters 26-30
				return $f($d);
			} else if ($__hx__switch === 1) {
				#/Users/ut/haxe/haxe_libraries/tink_core/1.20.0/haxelib/src/tink/core/Outcome.hx:158: characters 22-23
				$f1 = $o->params[0];
				#/Users/ut/haxe/haxe_libraries/tink_core/1.20.0/haxelib/src/tink/core/Outcome.hx:158: characters 26-36
				return Outcome::Failure($f1);
			}
		});
	}
}

Boot::registerClass(OutcomeMapper_Impl_::class, 'tink.core._Outcome.OutcomeMapper_Impl_');
