<?php
/**
 * Generated by Haxe 4.0.0-rc.2+77068e1
 * Haxe source file: src/views/Layout.hx
 */

namespace views;

use \views\__impl\Head as __implHead;
use \php\Boot;
use \tink\template\_Html\Html_Impl_;
use \tink\template\_Html\HtmlBuffer_Impl_;

class Layout {
	/**
	 * @var Layout
	 */
	static public $_instance;

	/**
	 * @var string
	 */
	public $footer;
	/**
	 * @var string
	 */
	public $head;
	/**
	 * @var string
	 */
	public $header;
	/**
	 * @var string
	 */
	public $id;
	/**
	 * @var string
	 */
	public $menu;
	/**
	 * @var \Array_hx
	 */
	public $scripts;
	/**
	 * @var string
	 */
	public $viewContent;

	/**
	 * @return Layout
	 */
	static public function get_instance () {
		#src/views/Layout.hx:22: lines 22-23
		if (Layout::$_instance === null) {
			#src/views/Layout.hx:23: characters 13-37
			Layout::$_instance = new Layout();
		}
		#src/views/Layout.hx:24: characters 9-25
		return Layout::$_instance;
	}

	/**
	 * @param string $v
	 * @param string $contentid
	 * 
	 * @return Layout
	 */
	static public function withLayout ($v, $contentid = "layout") {
		#src/views/Layout.hx:29: lines 29-36
		if ($contentid === null) {
			$contentid = "layout";
		}
		#src/views/Layout.hx:31: characters 9-31
		Layout::get_instance()->init();
		#src/views/Layout.hx:32: characters 9-38
		Layout::get_instance()->viewContent = $v;
		#src/views/Layout.hx:33: characters 9-37
		Layout::get_instance()->id = $contentid;
		#src/views/Layout.hx:34: characters 9-31
		return Layout::get_instance();
	}

	/**
	 * @return void
	 */
	public function __construct () {
		#src/views/Layout.hx:14: characters 39-41
		$this->scripts = new \Array_hx();
	}

	/**
	 * @param string $actions
	 * 
	 * @return Layout
	 */
	public function addAct ($actions) {
		#src/views/Layout.hx:47: characters 9-48
		$this->head = __implHead::render($this->scripts, $actions);
		#src/views/Layout.hx:48: characters 9-20
		return $this;
	}

	/**
	 * @param string $script
	 * 
	 * @return Layout
	 */
	public function addScript ($script) {
		#src/views/Layout.hx:40: lines 40-41
		if (!\Lambda::has($this->scripts, $script)) {
			#src/views/Layout.hx:41: characters 13-33
			$_this = $this->scripts;
			$_this->arr[$_this->length] = $script;
			++$_this->length;
		}
		#src/views/Layout.hx:42: characters 13-24
		return $this;
	}

	/**
	 * @return Layout
	 */
	public function init () {
		#src/views/Layout.hx:53: characters 9-45
		$this->head = __implHead::render($this->scripts, null);
		#src/views/Layout.hx:54: characters 9-20
		return $this;
	}

	/**
	 * @return string
	 */
	public function render () {
		#src//views/layout.tt:1: character 1
		$ret = Html_Impl_::buffer();
		$ret->arr[$ret->length] = "<!-- POSITION: {\"min\":0,\"max\":0,\"file\":\"src//views/layout.tt\"} -->";
		++$ret->length;

		$ret->arr[$ret->length] = "<!DOCTYPE html>\x0A<html lang=\"en\">\x0A    ";
		++$ret->length;

		#src//views/layout.tt:1: characters 40-44
		$ret->arr[$ret->length] = $this->head;
		++$ret->length;

		#src//views/layout.tt:1: characters 40-46
		$ret->arr[$ret->length] = "\x0A<body>\x0A<div class=\"maincontainer\" id=\"";
		++$ret->length;

		#src//views/layout.tt:1: characters 87-89
		$b = Html_Impl_::escape($this->id);
		$ret->arr[$ret->length] = $b;
		++$ret->length;

		#src//views/layout.tt:1: characters 87-91
		$ret->arr[$ret->length] = "\">\x0A    \x0A    <div class=\"container\">\x0A        ";
		++$ret->length;

		#src//views/layout.tt:1: characters 137-143
		$ret->arr[$ret->length] = $this->header;
		++$ret->length;

		#src//views/layout.tt:1: characters 137-145
		$ret->arr[$ret->length] = "\x0A        ";
		++$ret->length;

		#src//views/layout.tt:1: characters 156-160
		$ret->arr[$ret->length] = $this->menu;
		++$ret->length;

		#src//views/layout.tt:1: characters 156-162
		$ret->arr[$ret->length] = "\x0A        ";
		++$ret->length;

		#src//views/layout.tt:1: characters 174-185
		$ret->arr[$ret->length] = $this->viewContent;
		++$ret->length;

		#src//views/layout.tt:1: characters 174-188
		$ret->arr[$ret->length] = "\x0A        ";
		++$ret->length;

		#src//views/layout.tt:1: characters 200-206
		$ret->arr[$ret->length] = $this->footer;
		++$ret->length;

		#src//views/layout.tt:1: characters 200-209
		$ret->arr[$ret->length] = "\x0A    </div>\x0A</div>\x0A</body>\x0A</html>";
		++$ret->length;



		#/Users/ut/haxe/haxe_libraries/tink_template/0.3.3/github/dcf3c80c34ba368d9b8d06f42c6c25640ec9d7f5/src/tink/template/Generator.hx:121: characters 19-30
		return HtmlBuffer_Impl_::collapse($ret);
	}
}

Boot::registerClass(Layout::class, 'views.Layout');
Boot::registerGetters('views\\Layout', [
	'instance' => true
]);
