<?php
/**
 * Generated by Haxe 4.0.0-rc.2+77068e1
 * Haxe source file: /Users/ut/haxe/haxe_libraries/tink_core/1.20.0/haxelib/src/tink/core/Ref.hx
 */

namespace tink\core\_Ref;

use \php\Boot;
use \haxe\ds\_Vector\PhpVectorData;

final class Ref_Impl_ {

	/**
	 * @return PhpVectorData
	 */
	static public function _new () {
		#/Users/ut/haxe/haxe_libraries/tink_core/1.20.0/haxelib/src/tink/core/Ref.hx:6: characters 32-53
		$this1 = new PhpVectorData(1);
		#/Users/ut/haxe/haxe_libraries/tink_core/1.20.0/haxelib/src/tink/core/Ref.hx:6: character 3
		$this2 = $this1;
		return $this2;
	}

	/**
	 * @param PhpVectorData $this
	 * 
	 * @return mixed
	 */
	static public function get_value ($this1) {
		#/Users/ut/haxe/haxe_libraries/tink_core/1.20.0/haxelib/src/tink/core/Ref.hx:8: characters 38-52
		return ($this1->data[0] ?? null);
	}

	/**
	 * @param PhpVectorData $this
	 * @param mixed $param
	 * 
	 * @return mixed
	 */
	static public function set_value ($this1, $param) {
		#/Users/ut/haxe/haxe_libraries/tink_core/1.20.0/haxelib/src/tink/core/Ref.hx:9: characters 38-60
		return $this1->data[0] = $param;
	}

	/**
	 * @param mixed $v
	 * 
	 * @return PhpVectorData
	 */
	static public function to ($v) {
		#/Users/ut/haxe/haxe_libraries/tink_core/1.20.0/haxelib/src/tink/core/Ref.hx:14: characters 15-24
		$this1 = new PhpVectorData(1);
		$this2 = $this1;
		#/Users/ut/haxe/haxe_libraries/tink_core/1.20.0/haxelib/src/tink/core/Ref.hx:14: characters 5-25
		$ret = $this2;
		#/Users/ut/haxe/haxe_libraries/tink_core/1.20.0/haxelib/src/tink/core/Ref.hx:15: characters 5-18
		$ret->data[0] = $v;
		#/Users/ut/haxe/haxe_libraries/tink_core/1.20.0/haxelib/src/tink/core/Ref.hx:16: characters 5-15
		return $ret;
	}

	/**
	 * @param PhpVectorData $this
	 * 
	 * @return string
	 */
	static public function toString ($this1) {
		#/Users/ut/haxe/haxe_libraries/tink_core/1.20.0/haxelib/src/tink/core/Ref.hx:11: characters 37-72
		return "@[" . (\Std::string(($this1->data[0] ?? null))??'null') . "]";
	}
}

Boot::registerClass(Ref_Impl_::class, 'tink.core._Ref.Ref_Impl_');
Boot::registerGetters('tink\\core\\_Ref\\Ref_Impl_', [
	'value' => true
]);
Boot::registerSetters('tink\\core\\_Ref\\Ref_Impl_', [
	'value' => true
]);
