<?php
/**
 * Generated by Haxe 4.0.0-rc.2+77068e1
 * Haxe source file: /Users/ut/haxe/haxe_libraries/tink_template/0.3.3/github/dcf3c80c34ba368d9b8d06f42c6c25640ec9d7f5/src/tink/template/Html.hx
 */

namespace tink\template\_Html;

use \php\Boot;
use \php\_Boot\HxString;

final class Html_Impl_ {
	/**
	 * @param string $s
	 * 
	 * @return string
	 */
	static public function _new ($s) {
		#/Users/ut/haxe/haxe_libraries/tink_template/0.3.3/github/dcf3c80c34ba368d9b8d06f42c6c25640ec9d7f5/src/tink/template/Html.hx:5: character 3
		return $s;
	}

	/**
	 * @return \Array_hx
	 */
	static public function buffer () {
		#/Users/ut/haxe/haxe_libraries/tink_template/0.3.3/github/dcf3c80c34ba368d9b8d06f42c6c25640ec9d7f5/src/tink/template/Html.hx:44: characters 12-28
		$this1 = new \Array_hx();
		return $this1;
	}

	/**
	 * @param string $s
	 * 
	 * @return string
	 */
	static public function escape ($s) {
		#/Users/ut/haxe/haxe_libraries/tink_template/0.3.3/github/dcf3c80c34ba368d9b8d06f42c6c25640ec9d7f5/src/tink/template/Html.hx:8: characters 5-31
		if ($s === null) {
			#/Users/ut/haxe/haxe_libraries/tink_template/0.3.3/github/dcf3c80c34ba368d9b8d06f42c6c25640ec9d7f5/src/tink/template/Html.hx:8: characters 20-31
			return null;
		}
		#/Users/ut/haxe/haxe_libraries/tink_template/0.3.3/github/dcf3c80c34ba368d9b8d06f42c6c25640ec9d7f5/src/tink/template/Html.hx:9: characters 5-22
		$s = \Std::string($s);
		#/Users/ut/haxe/haxe_libraries/tink_template/0.3.3/github/dcf3c80c34ba368d9b8d06f42c6c25640ec9d7f5/src/tink/template/Html.hx:10: lines 10-12
		$start = 0;
		$pos = 0;
		$max = mb_strlen($s);
		#/Users/ut/haxe/haxe_libraries/tink_template/0.3.3/github/dcf3c80c34ba368d9b8d06f42c6c25640ec9d7f5/src/tink/template/Html.hx:13: characters 5-18
		$ret = "";
		#/Users/ut/haxe/haxe_libraries/tink_template/0.3.3/github/dcf3c80c34ba368d9b8d06f42c6c25640ec9d7f5/src/tink/template/Html.hx:22: lines 22-28
		while ($pos < $max) {
			#/Users/ut/haxe/haxe_libraries/tink_template/0.3.3/github/dcf3c80c34ba368d9b8d06f42c6c25640ec9d7f5/src/tink/template/Html.hx:23: characters 23-28
			$index = $pos++;
			#/Users/ut/haxe/haxe_libraries/tink_template/0.3.3/github/dcf3c80c34ba368d9b8d06f42c6c25640ec9d7f5/src/tink/template/Html.hx:23: characters 14-29
			$__hx__switch = (($index < 0 ? "" : mb_substr($s, $index, 1)));
			if ($__hx__switch === "\"") {
				#/Users/ut/haxe/haxe_libraries/tink_template/0.3.3/github/dcf3c80c34ba368d9b8d06f42c6c25640ec9d7f5/src/tink/template/Html.hx:24: characters 19-34
				$start1 = $start;
				$start = $pos;
				$ret = ($ret??'null') . (HxString::substring($s, $start1, $start - 1)??'null') . "&quot;";
			} else if ($__hx__switch === "&") {
				#/Users/ut/haxe/haxe_libraries/tink_template/0.3.3/github/dcf3c80c34ba368d9b8d06f42c6c25640ec9d7f5/src/tink/template/Html.hx:27: characters 19-33
				$start2 = $start;
				$start = $pos;
				$ret = ($ret??'null') . (HxString::substring($s, $start2, $start - 1)??'null') . "&amp;";
			} else if ($__hx__switch === "<") {
				#/Users/ut/haxe/haxe_libraries/tink_template/0.3.3/github/dcf3c80c34ba368d9b8d06f42c6c25640ec9d7f5/src/tink/template/Html.hx:25: characters 19-32
				$start3 = $start;
				$start = $pos;
				$ret = ($ret??'null') . (HxString::substring($s, $start3, $start - 1)??'null') . "&lt;";
			} else if ($__hx__switch === ">") {
				#/Users/ut/haxe/haxe_libraries/tink_template/0.3.3/github/dcf3c80c34ba368d9b8d06f42c6c25640ec9d7f5/src/tink/template/Html.hx:26: characters 19-32
				$start4 = $start;
				$start = $pos;
				$ret = ($ret??'null') . (HxString::substring($s, $start4, $start - 1)??'null') . "&gt;";
			}
		}
		#/Users/ut/haxe/haxe_libraries/tink_template/0.3.3/github/dcf3c80c34ba368d9b8d06f42c6c25640ec9d7f5/src/tink/template/Html.hx:30: characters 5-12
		$ret = ($ret??'null') . (mb_substr($s, $start, null)??'null');
		#/Users/ut/haxe/haxe_libraries/tink_template/0.3.3/github/dcf3c80c34ba368d9b8d06f42c6c25640ec9d7f5/src/tink/template/Html.hx:31: characters 12-25
		$this1 = $ret;
		return $this1;
	}

	/**
	 * @param mixed $a
	 * 
	 * @return string
	 */
	static public function of ($a) {
		#/Users/ut/haxe/haxe_libraries/tink_template/0.3.3/github/dcf3c80c34ba368d9b8d06f42c6c25640ec9d7f5/src/tink/template/Html.hx:41: characters 5-33
		return Html_Impl_::escape(\Std::string($a));
	}

	/**
	 * @param \Array_hx $parts
	 * 
	 * @return string
	 */
	static public function ofMultiple ($parts) {
		#/Users/ut/haxe/haxe_libraries/tink_template/0.3.3/github/dcf3c80c34ba368d9b8d06f42c6c25640ec9d7f5/src/tink/template/Html.hx:38: characters 12-36
		return $parts->join("");
	}

	/**
	 * @param string $this
	 * 
	 * @return string
	 */
	static public function toString ($this1) {
		#/Users/ut/haxe/haxe_libraries/tink_template/0.3.3/github/dcf3c80c34ba368d9b8d06f42c6c25640ec9d7f5/src/tink/template/Html.hx:35: characters 5-16
		return $this1;
	}
}

Boot::registerClass(Html_Impl_::class, 'tink.template._Html.Html_Impl_');
