<?php
/**
 * Generated by Haxe 4.0.0-rc.2+77068e1
 * Haxe source file: /Users/ut/haxe/haxe_libraries/tink_http/0.8.2/github/c95e2dc46654779b496e5f99d01241b1d572e33c/src/tink/http/Message.hx
 */

namespace tink\http;

use \php\Boot;

class Message {
	/**
	 * @var mixed
	 */
	public $body;
	/**
	 * @var mixed
	 */
	public $header;

	/**
	 * @param mixed $header
	 * @param mixed $body
	 * 
	 * @return void
	 */
	public function __construct ($header, $body) {
		#/Users/ut/haxe/haxe_libraries/tink_http/0.8.2/github/c95e2dc46654779b496e5f99d01241b1d572e33c/src/tink/http/Message.hx:9: characters 5-25
		$this->header = $header;
		#/Users/ut/haxe/haxe_libraries/tink_http/0.8.2/github/c95e2dc46654779b496e5f99d01241b1d572e33c/src/tink/http/Message.hx:10: characters 5-21
		$this->body = $body;
	}
}

Boot::registerClass(Message::class, 'tink.http.Message');
