<?php
/**
 * Generated by Haxe 4.0.0-rc.2+77068e1
 * Haxe source file: /Users/ut/haxe/haxe_libraries/tink_http/0.8.2/github/c95e2dc46654779b496e5f99d01241b1d572e33c/src/tink/http/Request.hx
 */

namespace tink\http;

use \php\Boot;

class OutgoingRequestHeader extends RequestHeader {
	/**
	 * @param string $method
	 * @param object $url
	 * @param string $protocol
	 * @param \Array_hx $fields
	 * 
	 * @return void
	 */
	public function __construct ($method, $url, $protocol = null, $fields) {
		#/Users/ut/haxe/haxe_libraries/tink_http/0.8.2/github/c95e2dc46654779b496e5f99d01241b1d572e33c/src/tink/http/Request.hx:113: lines 113-116
		parent::__construct($method, $url, $protocol, $fields);
	}

	/**
	 * @param \Array_hx $fields
	 * 
	 * @return OutgoingRequestHeader
	 */
	public function concat ($fields) {
		#/Users/ut/haxe/haxe_libraries/tink_http/0.8.2/github/c95e2dc46654779b496e5f99d01241b1d572e33c/src/tink/http/Request.hx:115: characters 38-44
		$tmp = $this->method;
		#/Users/ut/haxe/haxe_libraries/tink_http/0.8.2/github/c95e2dc46654779b496e5f99d01241b1d572e33c/src/tink/http/Request.hx:115: characters 46-49
		$tmp1 = $this->url;
		#/Users/ut/haxe/haxe_libraries/tink_http/0.8.2/github/c95e2dc46654779b496e5f99d01241b1d572e33c/src/tink/http/Request.hx:115: characters 51-59
		$tmp2 = $this->protocol;
		#/Users/ut/haxe/haxe_libraries/tink_http/0.8.2/github/c95e2dc46654779b496e5f99d01241b1d572e33c/src/tink/http/Request.hx:115: characters 5-88
		return new OutgoingRequestHeader($tmp, $tmp1, $tmp2, $this->fields->concat($fields));
	}
}

Boot::registerClass(OutgoingRequestHeader::class, 'tink.http.OutgoingRequestHeader');
