<?php
/**
 * Generated by Haxe 4.0.0-rc.2+77068e1
 * Haxe source file: /Users/ut/haxe/haxe_libraries/tink_http/0.8.2/github/c95e2dc46654779b496e5f99d01241b1d572e33c/src/tink/http/Request.hx
 */

namespace tink\http;

use \php\Boot;
use \tink\streams\StreamObject;

class OutgoingRequest extends Message {
	/**
	 * @param OutgoingRequestHeader $header
	 * @param StreamObject $body
	 * 
	 * @return void
	 */
	public function __construct ($header, $body) {
		#/Users/ut/haxe/haxe_libraries/tink_http/0.8.2/github/c95e2dc46654779b496e5f99d01241b1d572e33c/src/tink/http/Request.hx:118: characters 1-77
		parent::__construct($header, $body);
	}
}

Boot::registerClass(OutgoingRequest::class, 'tink.http.OutgoingRequest');
