<?php
/**
 * Generated by Haxe 4.0.0-rc.2+77068e1
 * Haxe source file: /Users/ut/haxe/haxe_libraries/tink_http_middleware/0.1.0/github/82c73bb5c4cd37a67f711b71a42e7ec2031d6894/src/tink/http/Middleware.hx
 */

namespace tink\http;

use \php\Boot;

class SimpleMiddleware implements MiddlewareObject {
	/**
	 * @var \Closure
	 */
	public $f;

	/**
	 * @param \Closure $f
	 * 
	 * @return void
	 */
	public function __construct ($f) {
		#/Users/ut/haxe/haxe_libraries/tink_http_middleware/0.1.0/github/82c73bb5c4cd37a67f711b71a42e7ec2031d6894/src/tink/http/Middleware.hx:18: characters 5-15
		$this->f = $f;
	}

	/**
	 * @param HandlerObject $handler
	 * 
	 * @return HandlerObject
	 */
	public function apply ($handler) {
		#/Users/ut/haxe/haxe_libraries/tink_http_middleware/0.1.0/github/82c73bb5c4cd37a67f711b71a42e7ec2031d6894/src/tink/http/Middleware.hx:21: characters 5-22
		return ($this->f)($handler);
	}
}

Boot::registerClass(SimpleMiddleware::class, 'tink.http.SimpleMiddleware');
