<?php
/**
 * Generated by Haxe 4.0.0-rc.2+77068e1
 * Haxe source file: /Users/ut/haxe/haxe_libraries/tink_web/0.1.4/github/c4323c7b0c2f0b44e696eea51c9bfdff41716880/src/tink/web/routing/Context.hx
 */

namespace tink\web\routing\_Context;

use \php\Boot;
use \tink\url\_Portion\Portion_Impl_;

final class Path_Impl_ {
	/**
	 * @param \Array_hx $this
	 * 
	 * @return string
	 */
	static public function toString ($this1) {
		#/Users/ut/haxe/haxe_libraries/tink_web/0.1.4/github/c4323c7b0c2f0b44e696eea51c9bfdff41716880/src/tink/web/routing/Context.hx:20: characters 16-44
		$_g = new \Array_hx();
		#/Users/ut/haxe/haxe_libraries/tink_web/0.1.4/github/c4323c7b0c2f0b44e696eea51c9bfdff41716880/src/tink/web/routing/Context.hx:20: characters 17-43
		$_g1 = 0;
		while ($_g1 < $this1->length) {
			#/Users/ut/haxe/haxe_libraries/tink_web/0.1.4/github/c4323c7b0c2f0b44e696eea51c9bfdff41716880/src/tink/web/routing/Context.hx:20: characters 22-23
			$p = ($this1->arr[$_g1] ?? null);
			#/Users/ut/haxe/haxe_libraries/tink_web/0.1.4/github/c4323c7b0c2f0b44e696eea51c9bfdff41716880/src/tink/web/routing/Context.hx:20: characters 17-43
			++$_g1;
			#/Users/ut/haxe/haxe_libraries/tink_web/0.1.4/github/c4323c7b0c2f0b44e696eea51c9bfdff41716880/src/tink/web/routing/Context.hx:20: characters 33-43
			$x = Portion_Impl_::stringly($p);
			$_g->arr[$_g->length] = $x;
			++$_g->length;

		}

		#/Users/ut/haxe/haxe_libraries/tink_web/0.1.4/github/c4323c7b0c2f0b44e696eea51c9bfdff41716880/src/tink/web/routing/Context.hx:20: characters 5-54
		return "/" . ($_g->join("/")??'null');
	}
}

Boot::registerClass(Path_Impl_::class, 'tink.web.routing._Context.Path_Impl_');
