<?php
/**
 * Generated by Haxe 4.0.0-rc.1+1fdd3d5
 * Haxe source file: /Users/ut/haxe/haxe_libraries/geojson/0.9.7/haxelib/src/geojson/util/Lines.hx
 */

namespace geojson\util\_Lines;

use \php\Boot;

final class Lines_Impl_ {

	/**
	 * @param \Array_hx $lines
	 * 
	 * @return \Array_hx
	 */
	static public function _new ($lines) {
		#/Users/ut/haxe/haxe_libraries/geojson/0.9.7/haxelib/src/geojson/util/Lines.hx:8: character 2
		return $lines;
	}

	/**
	 * @param \Array_hx $this
	 * 
	 * @return \Array_hx
	 */
	static public function get_lines ($this1) {
		#/Users/ut/haxe/haxe_libraries/geojson/0.9.7/haxelib/src/geojson/util/Lines.hx:11: characters 30-41
		return $this1;
	}

	/**
	 * @param \Array_hx $this
	 * @param \Array_hx $v
	 * 
	 * @return \Array_hx
	 */
	static public function set_lines ($this1, $v) {
		#/Users/ut/haxe/haxe_libraries/geojson/0.9.7/haxelib/src/geojson/util/Lines.hx:12: characters 38-46
		$this1 = $v;
		#/Users/ut/haxe/haxe_libraries/geojson/0.9.7/haxelib/src/geojson/util/Lines.hx:12: characters 31-46
		return $v;
	}
}

Boot::registerClass(Lines_Impl_::class, 'geojson.util._Lines.Lines_Impl_');
Boot::registerGetters('geojson\\util\\_Lines\\Lines_Impl_', [
	'lines' => true
]);
Boot::registerSetters('geojson\\util\\_Lines\\Lines_Impl_', [
	'lines' => true
]);
