<?php
/**
 * Generated by Haxe 4.0.0-rc.2+77068e1
 * Haxe source file: /Users/ut/haxe/haxe_libraries/tink_http/0.8.2/github/c95e2dc46654779b496e5f99d01241b1d572e33c/src/tink/http/Method.hx
 */

namespace tink\http\_Method;

use \php\Boot;

final class Method_Impl_ {

	/**
	 * @param string $s
	 * @param \Closure $fallback
	 * 
	 * @return string
	 */
	static public function ofString ($s, $fallback) {
		#/Users/ut/haxe/haxe_libraries/tink_http/0.8.2/github/c95e2dc46654779b496e5f99d01241b1d572e33c/src/tink/http/Method.hx:14: characters 19-34
		$_g = mb_strtoupper($s);
		if ($_g === "DELETE") {
			#/Users/ut/haxe/haxe_libraries/tink_http/0.8.2/github/c95e2dc46654779b496e5f99d01241b1d572e33c/src/tink/http/Method.hx:21: characters 22-28
			return "DELETE";
		} else if ($_g === "GET") {
			#/Users/ut/haxe/haxe_libraries/tink_http/0.8.2/github/c95e2dc46654779b496e5f99d01241b1d572e33c/src/tink/http/Method.hx:15: characters 19-22
			return "GET";
		} else if ($_g === "HEAD") {
			#/Users/ut/haxe/haxe_libraries/tink_http/0.8.2/github/c95e2dc46654779b496e5f99d01241b1d572e33c/src/tink/http/Method.hx:16: characters 20-24
			return "HEAD";
		} else if ($_g === "OPTIONS") {
			#/Users/ut/haxe/haxe_libraries/tink_http/0.8.2/github/c95e2dc46654779b496e5f99d01241b1d572e33c/src/tink/http/Method.hx:17: characters 23-30
			return "OPTIONS";
		} else if ($_g === "PATCH") {
			#/Users/ut/haxe/haxe_libraries/tink_http/0.8.2/github/c95e2dc46654779b496e5f99d01241b1d572e33c/src/tink/http/Method.hx:20: characters 21-26
			return "PATCH";
		} else if ($_g === "POST") {
			#/Users/ut/haxe/haxe_libraries/tink_http/0.8.2/github/c95e2dc46654779b496e5f99d01241b1d572e33c/src/tink/http/Method.hx:18: characters 20-24
			return "POST";
		} else if ($_g === "PUT") {
			#/Users/ut/haxe/haxe_libraries/tink_http/0.8.2/github/c95e2dc46654779b496e5f99d01241b1d572e33c/src/tink/http/Method.hx:19: characters 19-22
			return "PUT";
		} else {
			#/Users/ut/haxe/haxe_libraries/tink_http/0.8.2/github/c95e2dc46654779b496e5f99d01241b1d572e33c/src/tink/http/Method.hx:22: characters 15-26
			return $fallback($_g);
		}
	}
}

Boot::registerClass(Method_Impl_::class, 'tink.http._Method.Method_Impl_');
