<?php
/**
 * Generated by Haxe 4.0.0-rc.2+77068e1
 * Haxe source file: src/command/MyCommand2.hx
 */

namespace command;

use \php\Boot;
use \wire\ICommand;

class MyCommand2 implements ICommand {
	/**
	 * @param mixed $data
	 * 
	 * @return void
	 */
	public function execute ($data = null) {
	}
}

Boot::registerClass(MyCommand2::class, 'command.MyCommand2');
